import axios from 'axios';
import React, { useState } from 'react';
import useDataStore from '../../store/dataStore';
import useCredentialsStore from '../../store/credentialsStore';
import useSchemaStore from '../../store/schemaStore';
import RowInput from './RowInput';

type InputModalProps = {
  closeInputModal: () => void;
  tableNameProp?: string;
};

type DataObj = {
  [key:string]: string | number | boolean | null
}

type DataRowArray = Array<string | number | boolean | null>

export default function DataInputModal({
  closeInputModal,
  tableNameProp,
}: InputModalProps) {

  const [tableName] = useState(tableNameProp);
  const [rowData, setRowData] = useState<DataRowArray>([]);
  const { schemaStore } = useSchemaStore((state) => state);
  const { dbCredentials } = useCredentialsStore((state) => state);
  const { dataStore, setDataStore } = useDataStore((state) => state);

  const updatingDB = (newRow: Array<DataObj>):void => {
    axios
      .post(`api/sql/${dbCredentials.db_type}/data`, {tableName: tableName, newRow: newRow})
      .then((res) => {
        console.log('data has been sent to DB');
      })
      .catch((err: ErrorEvent) => { console.error('sending new row error', err) })
  }

  const secondaryColumnNames: string[] = Object.keys(schemaStore['public.' + tableName])

  const deepCopyDataStore = JSON.parse(JSON.stringify(dataStore))
  const currentTable = deepCopyDataStore[tableName]  

  const handleSubmit = (): boolean => { 
    try {
      const additionalRow: Record<string, string | number | boolean | null> = {};
      if (!currentTable.length) {
        secondaryColumnNames.forEach((columnName, i) => {
          additionalRow[columnName] = rowData[i];
        });
      } else {
        Object.keys(currentTable[0]).forEach((columnName, i) => {
          additionalRow[columnName] = rowData[i];
        });
      }
      currentTable.push(additionalRow)
      updatingDB(currentTable[currentTable.length - 1])

      //TODO: in case if we can tell which value needs to be gen by DB...
      //if there is value that needs to be generated by DB

      //fetch updated data from DB
      const getUpdatedData = axios
       .get(`api/sql/${dbCredentials.db_type}/schema`, { params: dbCredentials })
       .then(res => {
         setDataStore(res.data.data)
         return res.data
       })
        .catch((err: ErrorEvent) => console.error('getSchema error', err))
      
      //else, just update dataStore
      // setDataStore({...dataStore, [tableName]:currentTable})
      ////////////////////////////////////////////////////////////////
      return true;
    } catch (error) {
      window.alert(error);
      console.error(error);
      return false;
    }
  };

  const values: Array<string | number | boolean | null> = []

  const handleRowChange = (
    index: number,
    value: string | number | boolean | null
  ) => {
    values.push(value)

    //updating rowData
    setRowData((prevRows) => {
      prevRows[index] = value;
      return [...prevRows]
    })
  }

  return (
    <div id="inputModal" className="input-modal" >
      <form
        autoComplete="off"
        onSubmit={(e) => {
          e.preventDefault();
          const isSuccessful: boolean = handleSubmit();
          if (isSuccessful) closeInputModal();
        }}
        className="modal-content  rounded-md  bg-[#f8f4eb] shadow-[0px_5px_10px_rgba(0,0,0,0.4)] dark:bg-slate-800 dark:shadow-[0px_5px_10px_#1e293b]"
      >
        <div className="table-name">
          {<h1>{`Table Name: ${tableName}`}</h1>}
        </div>        
        <div className="column-header" >
          <h1 className="text-slate-900 dark:text-[#f8f4eb] flex-auto">
            {'New Row'}
          </h1>
        </div>
        <RowInput
          tableName={tableName}
          currentTable={currentTable}
          handleRowChange={handleRowChange}
          secondaryColumnNames={secondaryColumnNames}
        />
        <div className="mx-auto flex w-[50%] max-w-[200px] justify-between">
          <button
            type="button"
            className="modalButton text-slate-900 hover:opacity-70 dark:text-[#f8f4eb]"
            onClick={closeInputModal}
            data-testid="modal-cancel"
          >
            Cancel
          </button>
          <button
            className="modalButton text-slate-900 hover:opacity-70 dark:text-[#f8f4eb]"
            data-testid="modal-submit"
          >
            Add Row
          </button>
        </div>
      </form>
    </div>
  );
}
