export const swapiSchema = {
  'public.films': {
    _id: {
      Name: '_id',
      Value: null,
      TableName: 'public.films',
      References: [],
      IsPrimaryKey: true,
      IsForeignKey: false,
      field_name: '_id',
      data_type: 'INTEGER',
      additional_constraints: 'NOT NULL',
    },
    title: {
      Name: 'title',
      Value: null,
      TableName: 'public.films',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'title',
      data_type: 'VARCHAR(255)',
      additional_constraints: 'NOT NULL',
    },
    episode_id: {
      Name: 'episode_id',
      Value: null,
      TableName: 'public.films',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'episode_id',
      data_type: 'INTEGER',
      additional_constraints: 'NOT NULL',
    },
    opening_crawl: {
      Name: 'opening_crawl',
      Value: null,
      TableName: 'public.films',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'opening_crawl',
      data_type: 'VARCHAR(255)',
      additional_constraints: 'NOT NULL',
    },
    director: {
      Name: 'director',
      Value: null,
      TableName: 'public.films',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'director',
      data_type: 'VARCHAR(255)',
      additional_constraints: 'NOT NULL',
    },
    producer: {
      Name: 'producer',
      Value: null,
      TableName: 'public.films',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'producer',
      data_type: 'VARCHAR(255)',
      additional_constraints: 'NOT NULL',
    },
    release_date: {
      Name: 'release_date',
      Value: null,
      TableName: 'public.films',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'release_date',
      data_type: 'DATE',
      additional_constraints: 'NOT NULL',
    },
  },
  'public.people': {
    _id: {
      Name: '_id',
      Value: null,
      TableName: 'public.people',
      References: [],
      IsPrimaryKey: true,
      IsForeignKey: false,
      field_name: '_id',
      data_type: 'INTEGER',
      additional_constraints: 'NOT NULL',
    },
    name: {
      Name: 'name',
      Value: null,
      TableName: 'public.people',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'name',
      data_type: 'VARCHAR(255)',
      additional_constraints: 'NOT NULL',
    },
    mass: {
      Name: 'mass',
      Value: null,
      TableName: 'public.people',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'mass',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    hair_color: {
      Name: 'hair_color',
      Value: null,
      TableName: 'public.people',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'hair_color',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    skin_color: {
      Name: 'skin_color',
      Value: null,
      TableName: 'public.people',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'skin_color',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    eye_color: {
      Name: 'eye_color',
      Value: null,
      TableName: 'public.people',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'eye_color',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    birth_year: {
      Name: 'birth_year',
      Value: null,
      TableName: 'public.people',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'birth_year',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    gender: {
      Name: 'gender',
      Value: null,
      TableName: 'public.people',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'gender',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    species_id: {
      Name: 'species_id',
      Value: null,
      TableName: 'public.people',
      References: [
        {
          PrimaryKeyName: 'species_id',
          PrimaryKeyTableName: 'public.species',
          ReferencesPropertyName: 'species_id',
          ReferencesTableName: 'public.people',
          IsDestination: false,
          constraintName: 'people_fk0',
        },
      ],
      IsPrimaryKey: false,
      IsForeignKey: true,
      field_name: 'species_id',
      data_type: 'BIGINT',
      additional_constraints: null,
    },
    homeworld_id: {
      Name: 'homeworld_id',
      Value: null,
      TableName: 'public.people',
      References: [
        {
          PrimaryKeyName: 'homeworld_id',
          PrimaryKeyTableName: 'public.planets',
          ReferencesPropertyName: 'homeworld_id',
          ReferencesTableName: 'public.people',
          IsDestination: false,
          constraintName: 'people_fk1',
        },
      ],
      IsPrimaryKey: false,
      IsForeignKey: true,
      field_name: 'homeworld_id',
      data_type: 'BIGINT',
      additional_constraints: null,
    },
    height: {
      Name: 'height',
      Value: null,
      TableName: 'public.people',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'height',
      data_type: 'INTEGER',
      additional_constraints: null,
    },
  },
  'public.people_in_films': {
    _id: {
      Name: '_id',
      Value: null,
      TableName: 'public.people_in_films',
      References: [],
      IsPrimaryKey: true,
      IsForeignKey: false,
      field_name: '_id',
      data_type: 'INTEGER',
      additional_constraints: 'NOT NULL',
    },
    person_id: {
      Name: 'person_id',
      Value: null,
      TableName: 'public.people_in_films',
      References: [
        {
          PrimaryKeyName: 'person_id',
          PrimaryKeyTableName: 'public.people',
          ReferencesPropertyName: 'person_id',
          ReferencesTableName: 'public.people_in_films',
          IsDestination: false,
          constraintName: 'people_in_films_fk0',
        },
      ],
      IsPrimaryKey: false,
      IsForeignKey: true,
      field_name: 'person_id',
      data_type: 'BIGINT',
      additional_constraints: 'NOT NULL',
    },
    film_id: {
      Name: 'film_id',
      Value: null,
      TableName: 'public.people_in_films',
      References: [
        {
          PrimaryKeyName: 'film_id',
          PrimaryKeyTableName: 'public.films',
          ReferencesPropertyName: 'film_id',
          ReferencesTableName: 'public.people_in_films',
          IsDestination: false,
          constraintName: 'people_in_films_fk1',
        },
      ],
      IsPrimaryKey: false,
      IsForeignKey: true,
      field_name: 'film_id',
      data_type: 'BIGINT',
      additional_constraints: 'NOT NULL',
    },
  },
  'public.pilots': {
    _id: {
      Name: '_id',
      Value: null,
      TableName: 'public.pilots',
      References: [],
      IsPrimaryKey: true,
      IsForeignKey: false,
      field_name: '_id',
      data_type: 'INTEGER',
      additional_constraints: 'NOT NULL',
    },
    person_id: {
      Name: 'person_id',
      Value: null,
      TableName: 'public.pilots',
      References: [
        {
          PrimaryKeyName: 'person_id',
          PrimaryKeyTableName: 'public.people',
          ReferencesPropertyName: 'person_id',
          ReferencesTableName: 'public.pilots',
          IsDestination: false,
          constraintName: 'pilots_fk0',
        },
      ],
      IsPrimaryKey: false,
      IsForeignKey: true,
      field_name: 'person_id',
      data_type: 'BIGINT',
      additional_constraints: 'NOT NULL',
    },
    vessel_id: {
      Name: 'vessel_id',
      Value: null,
      TableName: 'public.pilots',
      References: [
        {
          PrimaryKeyName: 'vessel_id',
          PrimaryKeyTableName: 'public.vessels',
          ReferencesPropertyName: 'vessel_id',
          ReferencesTableName: 'public.pilots',
          IsDestination: false,
          constraintName: 'pilots_fk1',
        },
      ],
      IsPrimaryKey: false,
      IsForeignKey: true,
      field_name: 'vessel_id',
      data_type: 'BIGINT',
      additional_constraints: 'NOT NULL',
    },
  },
  'public.planets': {
    _id: {
      Name: '_id',
      Value: null,
      TableName: 'public.planets',
      References: [],
      IsPrimaryKey: true,
      IsForeignKey: false,
      field_name: '_id',
      data_type: 'INTEGER',
      additional_constraints: 'NOT NULL',
    },
    name: {
      Name: 'name',
      Value: null,
      TableName: 'public.planets',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'name',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    rotation_period: {
      Name: 'rotation_period',
      Value: null,
      TableName: 'public.planets',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'rotation_period',
      data_type: 'INTEGER',
      additional_constraints: null,
    },
    orbital_period: {
      Name: 'orbital_period',
      Value: null,
      TableName: 'public.planets',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'orbital_period',
      data_type: 'INTEGER',
      additional_constraints: null,
    },
    diameter: {
      Name: 'diameter',
      Value: null,
      TableName: 'public.planets',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'diameter',
      data_type: 'INTEGER',
      additional_constraints: null,
    },
    climate: {
      Name: 'climate',
      Value: null,
      TableName: 'public.planets',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'climate',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    gravity: {
      Name: 'gravity',
      Value: null,
      TableName: 'public.planets',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'gravity',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    terrain: {
      Name: 'terrain',
      Value: null,
      TableName: 'public.planets',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'terrain',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    surface_water: {
      Name: 'surface_water',
      Value: null,
      TableName: 'public.planets',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'surface_water',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    population: {
      Name: 'population',
      Value: null,
      TableName: 'public.planets',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'population',
      data_type: 'BIGINT',
      additional_constraints: null,
    },
  },
  'public.planets_in_films': {
    _id: {
      Name: '_id',
      Value: null,
      TableName: 'public.planets_in_films',
      References: [],
      IsPrimaryKey: true,
      IsForeignKey: false,
      field_name: '_id',
      data_type: 'INTEGER',
      additional_constraints: 'NOT NULL',
    },
    film_id: {
      Name: 'film_id',
      Value: null,
      TableName: 'public.planets_in_films',
      References: [
        {
          PrimaryKeyName: 'film_id',
          PrimaryKeyTableName: 'public.films',
          ReferencesPropertyName: 'film_id',
          ReferencesTableName: 'public.planets_in_films',
          IsDestination: false,
          constraintName: 'planets_in_films_fk0',
        },
      ],
      IsPrimaryKey: false,
      IsForeignKey: true,
      field_name: 'film_id',
      data_type: 'BIGINT',
      additional_constraints: 'NOT NULL',
    },
    planet_id: {
      Name: 'planet_id',
      Value: null,
      TableName: 'public.planets_in_films',
      References: [
        {
          PrimaryKeyName: 'planet_id',
          PrimaryKeyTableName: 'public.planets',
          ReferencesPropertyName: 'planet_id',
          ReferencesTableName: 'public.planets_in_films',
          IsDestination: false,
          constraintName: 'planets_in_films_fk1',
        },
      ],
      IsPrimaryKey: false,
      IsForeignKey: true,
      field_name: 'planet_id',
      data_type: 'BIGINT',
      additional_constraints: 'NOT NULL',
    },
  },
  'public.species': {
    _id: {
      Name: '_id',
      Value: null,
      TableName: 'public.species',
      References: [],
      IsPrimaryKey: true,
      IsForeignKey: false,
      field_name: '_id',
      data_type: 'INTEGER',
      additional_constraints: 'NOT NULL',
    },
    name: {
      Name: 'name',
      Value: null,
      TableName: 'public.species',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'name',
      data_type: 'VARCHAR(255)',
      additional_constraints: 'NOT NULL',
    },
    classification: {
      Name: 'classification',
      Value: null,
      TableName: 'public.species',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'classification',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    average_height: {
      Name: 'average_height',
      Value: null,
      TableName: 'public.species',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'average_height',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    average_lifespan: {
      Name: 'average_lifespan',
      Value: null,
      TableName: 'public.species',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'average_lifespan',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    hair_colors: {
      Name: 'hair_colors',
      Value: null,
      TableName: 'public.species',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'hair_colors',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    skin_colors: {
      Name: 'skin_colors',
      Value: null,
      TableName: 'public.species',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'skin_colors',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    eye_colors: {
      Name: 'eye_colors',
      Value: null,
      TableName: 'public.species',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'eye_colors',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    language: {
      Name: 'language',
      Value: null,
      TableName: 'public.species',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'language',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    homeworld_id: {
      Name: 'homeworld_id',
      Value: null,
      TableName: 'public.species',
      References: [
        {
          PrimaryKeyName: 'homeworld_id',
          PrimaryKeyTableName: 'public.planets',
          ReferencesPropertyName: 'homeworld_id',
          ReferencesTableName: 'public.species',
          IsDestination: false,
          constraintName: 'species_fk0',
        },
      ],
      IsPrimaryKey: false,
      IsForeignKey: true,
      field_name: 'homeworld_id',
      data_type: 'BIGINT',
      additional_constraints: null,
    },
  },
  'public.species_in_films': {
    _id: {
      Name: '_id',
      Value: null,
      TableName: 'public.species_in_films',
      References: [],
      IsPrimaryKey: true,
      IsForeignKey: false,
      field_name: '_id',
      data_type: 'INTEGER',
      additional_constraints: 'NOT NULL',
    },
    film_id: {
      Name: 'film_id',
      Value: null,
      TableName: 'public.species_in_films',
      References: [
        {
          PrimaryKeyName: 'film_id',
          PrimaryKeyTableName: 'public.films',
          ReferencesPropertyName: 'film_id',
          ReferencesTableName: 'public.species_in_films',
          IsDestination: false,
          constraintName: 'species_in_films_fk0',
        },
      ],
      IsPrimaryKey: false,
      IsForeignKey: true,
      field_name: 'film_id',
      data_type: 'BIGINT',
      additional_constraints: 'NOT NULL',
    },
    species_id: {
      Name: 'species_id',
      Value: null,
      TableName: 'public.species_in_films',
      References: [
        {
          PrimaryKeyName: 'species_id',
          PrimaryKeyTableName: 'public.species',
          ReferencesPropertyName: 'species_id',
          ReferencesTableName: 'public.species_in_films',
          IsDestination: false,
          constraintName: 'species_in_films_fk1',
        },
      ],
      IsPrimaryKey: false,
      IsForeignKey: true,
      field_name: 'species_id',
      data_type: 'BIGINT',
      additional_constraints: 'NOT NULL',
    },
  },
  'public.starship_specs': {
    _id: {
      Name: '_id',
      Value: null,
      TableName: 'public.starship_specs',
      References: [],
      IsPrimaryKey: true,
      IsForeignKey: false,
      field_name: '_id',
      data_type: 'INTEGER',
      additional_constraints: 'NOT NULL',
    },
    hyperdrive_rating: {
      Name: 'hyperdrive_rating',
      Value: null,
      TableName: 'public.starship_specs',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'hyperdrive_rating',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    MGLT: {
      Name: 'MGLT',
      Value: null,
      TableName: 'public.starship_specs',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'MGLT',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    vessel_id: {
      Name: 'vessel_id',
      Value: null,
      TableName: 'public.starship_specs',
      References: [
        {
          PrimaryKeyName: 'vessel_id',
          PrimaryKeyTableName: 'public.vessels',
          ReferencesPropertyName: 'vessel_id',
          ReferencesTableName: 'public.starship_specs',
          IsDestination: false,
          constraintName: 'starship_specs_fk0',
        },
      ],
      IsPrimaryKey: false,
      IsForeignKey: true,
      field_name: 'vessel_id',
      data_type: 'BIGINT',
      additional_constraints: 'NOT NULL',
    },
  },
  'public.vessels': {
    _id: {
      Name: '_id',
      Value: null,
      TableName: 'public.vessels',
      References: [],
      IsPrimaryKey: true,
      IsForeignKey: false,
      field_name: '_id',
      data_type: 'INTEGER',
      additional_constraints: 'NOT NULL',
    },
    name: {
      Name: 'name',
      Value: null,
      TableName: 'public.vessels',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'name',
      data_type: 'VARCHAR(255)',
      additional_constraints: 'NOT NULL',
    },
    manufacturer: {
      Name: 'manufacturer',
      Value: null,
      TableName: 'public.vessels',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'manufacturer',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    model: {
      Name: 'model',
      Value: null,
      TableName: 'public.vessels',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'model',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    vessel_type: {
      Name: 'vessel_type',
      Value: null,
      TableName: 'public.vessels',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'vessel_type',
      data_type: 'VARCHAR(255)',
      additional_constraints: 'NOT NULL',
    },
    vessel_class: {
      Name: 'vessel_class',
      Value: null,
      TableName: 'public.vessels',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'vessel_class',
      data_type: 'VARCHAR(255)',
      additional_constraints: 'NOT NULL',
    },
    cost_in_credits: {
      Name: 'cost_in_credits',
      Value: null,
      TableName: 'public.vessels',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'cost_in_credits',
      data_type: 'BIGINT',
      additional_constraints: null,
    },
    length: {
      Name: 'length',
      Value: null,
      TableName: 'public.vessels',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'length',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    max_atmosphering_speed: {
      Name: 'max_atmosphering_speed',
      Value: null,
      TableName: 'public.vessels',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'max_atmosphering_speed',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    crew: {
      Name: 'crew',
      Value: null,
      TableName: 'public.vessels',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'crew',
      data_type: 'INTEGER',
      additional_constraints: null,
    },
    passengers: {
      Name: 'passengers',
      Value: null,
      TableName: 'public.vessels',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'passengers',
      data_type: 'INTEGER',
      additional_constraints: null,
    },
    cargo_capacity: {
      Name: 'cargo_capacity',
      Value: null,
      TableName: 'public.vessels',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'cargo_capacity',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
    consumables: {
      Name: 'consumables',
      Value: null,
      TableName: 'public.vessels',
      References: [],
      IsPrimaryKey: false,
      IsForeignKey: false,
      field_name: 'consumables',
      data_type: 'VARCHAR(255)',
      additional_constraints: null,
    },
  },
  'public.vessels_in_films': {
    _id: {
      Name: '_id',
      Value: null,
      TableName: 'public.vessels_in_films',
      References: [],
      IsPrimaryKey: true,
      IsForeignKey: false,
      field_name: '_id',
      data_type: 'INTEGER',
      additional_constraints: 'NOT NULL',
    },
    vessel_id: {
      Name: 'vessel_id',
      Value: null,
      TableName: 'public.vessels_in_films',
      References: [
        {
          PrimaryKeyName: 'vessel_id',
          PrimaryKeyTableName: 'public.vessels',
          ReferencesPropertyName: 'vessel_id',
          ReferencesTableName: 'public.vessels_in_films',
          IsDestination: false,
          constraintName: 'vessels_in_films_fk0',
        },
      ],
      IsPrimaryKey: false,
      IsForeignKey: true,
      field_name: 'vessel_id',
      data_type: 'BIGINT',
      additional_constraints: 'NOT NULL',
    },
    film_id: {
      Name: 'film_id',
      Value: null,
      TableName: 'public.vessels_in_films',
      References: [
        {
          PrimaryKeyName: 'film_id',
          PrimaryKeyTableName: 'public.films',
          ReferencesPropertyName: 'film_id',
          ReferencesTableName: 'public.vessels_in_films',
          IsDestination: false,
          constraintName: 'vessels_in_films_fk1',
        },
      ],
      IsPrimaryKey: false,
      IsForeignKey: true,
      field_name: 'film_id',
      data_type: 'BIGINT',
      additional_constraints: 'NOT NULL',
    },
  },
};

export const swapiString = JSON.stringify(swapiSchema);
