export const swapiData = {
  'public.species': [
    {
      _id: 5,
      name: 'Hutt',
      classification: 'gastropod',
      average_height: '300',
      average_lifespan: '1000',
      hair_colors: 'n/a',
      skin_colors: 'green, brown, tan',
      eye_colors: 'yellow, red',
      language: 'Huttese',
      homeworld_id: '24',
    },
    {
      _id: 6,
      name: "Yoda''s species",
      classification: 'mammal',
      average_height: '66',
      average_lifespan: '900',
      hair_colors: 'brown, white',
      skin_colors: 'green, yellow',
      eye_colors: 'brown, green, yellow',
      language: 'Galactic basic',
      homeworld_id: '28',
    },
    {
      _id: 7,
      name: 'Trandoshan',
      classification: 'reptile',
      average_height: '200',
      average_lifespan: 'unknown',
      hair_colors: 'none',
      skin_colors: 'brown, green',
      eye_colors: 'yellow, orange',
      language: 'Dosh',
      homeworld_id: '29',
    },
    {
      _id: 8,
      name: 'Mon Calamari',
      classification: 'amphibian',
      average_height: '160',
      average_lifespan: 'unknown',
      hair_colors: 'none',
      skin_colors: 'red, blue, brown, magenta',
      eye_colors: 'yellow',
      language: 'Mon Calamarian',
      homeworld_id: '31',
    },
    {
      _id: 9,
      name: 'Ewok',
      classification: 'mammal',
      average_height: '100',
      average_lifespan: 'unknown',
      hair_colors: 'white, brown, black',
      skin_colors: 'brown',
      eye_colors: 'orange, brown',
      language: 'Ewokese',
      homeworld_id: '7',
    },
    {
      _id: 10,
      name: 'Sullustan',
      classification: 'mammal',
      average_height: '180',
      average_lifespan: 'unknown',
      hair_colors: 'none',
      skin_colors: 'pale',
      eye_colors: 'black',
      language: 'Sullutese',
      homeworld_id: '33',
    },
    {
      _id: 11,
      name: 'Neimodian',
      classification: 'unknown',
      average_height: '180',
      average_lifespan: 'unknown',
      hair_colors: 'none',
      skin_colors: 'grey, green',
      eye_colors: 'red, pink',
      language: 'Neimoidia',
      homeworld_id: '18',
    },
    {
      _id: 12,
      name: 'Gungan',
      classification: 'amphibian',
      average_height: '190',
      average_lifespan: 'unknown',
      hair_colors: 'none',
      skin_colors: 'brown, green',
      eye_colors: 'orange',
      language: 'Gungan basic',
      homeworld_id: '8',
    },
    {
      _id: 13,
      name: 'Toydarian',
      classification: 'mammal',
      average_height: '120',
      average_lifespan: '91',
      hair_colors: 'none',
      skin_colors: 'blue, green, grey',
      eye_colors: 'yellow',
      language: 'Toydarian',
      homeworld_id: '34',
    },
    {
      _id: 14,
      name: 'Dug',
      classification: 'mammal',
      average_height: '100',
      average_lifespan: 'unknown',
      hair_colors: 'none',
      skin_colors: 'brown, purple, grey, red',
      eye_colors: 'yellow, blue',
      language: 'Dugese',
      homeworld_id: '35',
    },
    {
      _id: 15,
      name: "Twi''lek",
      classification: 'mammals',
      average_height: '200',
      average_lifespan: 'unknown',
      hair_colors: 'none',
      skin_colors: 'orange, yellow, blue, green, pink, purple, tan',
      eye_colors: 'blue, brown, orange, pink',
      language: "Twi''leki",
      homeworld_id: '37',
    },
    {
      _id: 16,
      name: 'Aleena',
      classification: 'reptile',
      average_height: '80',
      average_lifespan: '79',
      hair_colors: 'none',
      skin_colors: 'blue, gray',
      eye_colors: 'unknown',
      language: 'Aleena',
      homeworld_id: '38',
    },
    {
      _id: 17,
      name: 'Vulptereen',
      classification: 'unknown',
      average_height: '100',
      average_lifespan: 'unknown',
      hair_colors: 'none',
      skin_colors: 'grey',
      eye_colors: 'yellow',
      language: 'vulpterish',
      homeworld_id: '39',
    },
    {
      _id: 18,
      name: 'Xexto',
      classification: 'unknown',
      average_height: '125',
      average_lifespan: 'unknown',
      hair_colors: 'none',
      skin_colors: 'grey, yellow, purple',
      eye_colors: 'black',
      language: 'Xextese',
      homeworld_id: '40',
    },
    {
      _id: 19,
      name: 'Toong',
      classification: 'unknown',
      average_height: '200',
      average_lifespan: 'unknown',
      hair_colors: 'none',
      skin_colors: 'grey, green, yellow',
      eye_colors: 'orange',
      language: 'Tundan',
      homeworld_id: '41',
    },
    {
      _id: 20,
      name: 'Cerean',
      classification: 'mammal',
      average_height: '200',
      average_lifespan: 'unknown',
      hair_colors: 'red, blond, black, white',
      skin_colors: 'pale pink',
      eye_colors: 'hazel',
      language: 'Cerean',
      homeworld_id: '43',
    },
    {
      _id: 21,
      name: 'Nautolan',
      classification: 'amphibian',
      average_height: '180',
      average_lifespan: '70',
      hair_colors: 'none',
      skin_colors: 'green, blue, brown, red',
      eye_colors: 'black',
      language: 'Nautila',
      homeworld_id: '44',
    },
    {
      _id: 22,
      name: 'Zabrak',
      classification: 'mammal',
      average_height: '180',
      average_lifespan: 'unknown',
      hair_colors: 'black',
      skin_colors: 'pale, brown, red, orange, yellow',
      eye_colors: 'brown, orange',
      language: 'Zabraki',
      homeworld_id: '45',
    },
    {
      _id: 23,
      name: 'Tholothian',
      classification: 'mammal',
      average_height: 'unknown',
      average_lifespan: 'unknown',
      hair_colors: 'unknown',
      skin_colors: 'dark',
      eye_colors: 'blue, indigo',
      language: 'unknown',
      homeworld_id: '46',
    },
    {
      _id: 24,
      name: 'Iktotchi',
      classification: 'unknown',
      average_height: '180',
      average_lifespan: 'unknown',
      hair_colors: 'none',
      skin_colors: 'pink',
      eye_colors: 'orange',
      language: 'Iktotchese',
      homeworld_id: '47',
    },
    {
      _id: 25,
      name: 'Quermian',
      classification: 'mammal',
      average_height: '240',
      average_lifespan: '86',
      hair_colors: 'none',
      skin_colors: 'white',
      eye_colors: 'yellow',
      language: 'Quermian',
      homeworld_id: '48',
    },
    {
      _id: 26,
      name: 'Kel Dor',
      classification: 'unknown',
      average_height: '180',
      average_lifespan: '70',
      hair_colors: 'none',
      skin_colors: 'peach, orange, red',
      eye_colors: 'black, silver',
      language: 'Kel Dor',
      homeworld_id: '49',
    },
    {
      _id: 27,
      name: 'Chagrian',
      classification: 'amphibian',
      average_height: '190',
      average_lifespan: 'unknown',
      hair_colors: 'none',
      skin_colors: 'blue',
      eye_colors: 'blue',
      language: 'Chagria',
      homeworld_id: '50',
    },
    {
      _id: 28,
      name: 'Geonosian',
      classification: 'insectoid',
      average_height: '178',
      average_lifespan: 'unknown',
      hair_colors: 'none',
      skin_colors: 'green, brown',
      eye_colors: 'green, hazel',
      language: 'Geonosian',
      homeworld_id: '11',
    },
    {
      _id: 29,
      name: 'Mirialan',
      classification: 'mammal',
      average_height: '180',
      average_lifespan: 'unknown',
      hair_colors: 'black, brown',
      skin_colors: 'yellow, green',
      eye_colors: 'blue, green, red, yellow, brown, orange',
      language: 'Mirialan',
      homeworld_id: '51',
    },
    {
      _id: 30,
      name: 'Clawdite',
      classification: 'reptilian',
      average_height: '180',
      average_lifespan: '70',
      hair_colors: 'none',
      skin_colors: 'green, yellow',
      eye_colors: 'yellow',
      language: 'Clawdite',
      homeworld_id: '54',
    },
    {
      _id: 31,
      name: 'Besalisk',
      classification: 'amphibian',
      average_height: '178',
      average_lifespan: '75',
      hair_colors: 'none',
      skin_colors: 'brown',
      eye_colors: 'yellow',
      language: 'besalisk',
      homeworld_id: '55',
    },
    {
      _id: 32,
      name: 'Kaminoan',
      classification: 'amphibian',
      average_height: '220',
      average_lifespan: '80',
      hair_colors: 'none',
      skin_colors: 'grey, blue',
      eye_colors: 'black',
      language: 'Kaminoan',
      homeworld_id: '10',
    },
    {
      _id: 33,
      name: 'Skakoan',
      classification: 'mammal',
      average_height: 'unknown',
      average_lifespan: 'unknown',
      hair_colors: 'none',
      skin_colors: 'grey, green',
      eye_colors: 'unknown',
      language: 'Skakoan',
      homeworld_id: '56',
    },
    {
      _id: 34,
      name: 'Muun',
      classification: 'mammal',
      average_height: '190',
      average_lifespan: '100',
      hair_colors: 'none',
      skin_colors: 'grey, white',
      eye_colors: 'black',
      language: 'Muun',
      homeworld_id: '57',
    },
    {
      _id: 35,
      name: 'Togruta',
      classification: 'mammal',
      average_height: '180',
      average_lifespan: '94',
      hair_colors: 'none',
      skin_colors: 'red, white, orange, yellow, green, blue',
      eye_colors: 'red, orange, yellow, green, blue, black',
      language: 'Togruti',
      homeworld_id: '58',
    },
    {
      _id: 36,
      name: 'Kaleesh',
      classification: 'reptile',
      average_height: '170',
      average_lifespan: '80',
      hair_colors: 'none',
      skin_colors: 'brown, orange, tan',
      eye_colors: 'yellow',
      language: 'Kaleesh',
      homeworld_id: '59',
    },
    {
      _id: 37,
      name: "Pau''an",
      classification: 'mammal',
      average_height: '190',
      average_lifespan: '700',
      hair_colors: 'none',
      skin_colors: 'grey',
      eye_colors: 'black',
      language: 'Utapese',
      homeworld_id: '12',
    },
    {
      _id: 3,
      name: 'Wookiee',
      classification: 'mammal',
      average_height: '210',
      average_lifespan: '400',
      hair_colors: 'black, brown',
      skin_colors: 'gray',
      eye_colors: 'blue, green, yellow, brown, golden, red',
      language: 'Shyriiwook',
      homeworld_id: '14',
    },
    {
      _id: 2,
      name: 'Droid',
      classification: 'artificial',
      average_height: 'n/a',
      average_lifespan: 'indefinite',
      hair_colors: 'n/a',
      skin_colors: 'n/a',
      eye_colors: 'n/a',
      language: 'n/a',
      homeworld_id: null,
    },
    {
      _id: 1,
      name: 'Human',
      classification: 'mammal',
      average_height: '180',
      average_lifespan: '120',
      hair_colors: 'blonde, brown, black, red',
      skin_colors: 'caucasian, black, asian, hispanic',
      eye_colors: 'brown, blue, green, hazel, grey, amber',
      language: 'Galactic Basic',
      homeworld_id: '9',
    },
    {
      _id: 4,
      name: 'Rodian',
      classification: 'sentient',
      average_height: '170',
      average_lifespan: 'unknown',
      hair_colors: 'n/a',
      skin_colors: 'green, blue',
      eye_colors: 'black',
      language: 'Galactic Basic',
      homeworld_id: '23',
    },
  ],
  'public.people_in_films': [
    { _id: 1, person_id: '1', film_id: '1' },
    { _id: 2, person_id: '2', film_id: '1' },
    { _id: 3, person_id: '3', film_id: '1' },
    { _id: 4, person_id: '4', film_id: '1' },
    { _id: 5, person_id: '5', film_id: '1' },
    { _id: 6, person_id: '6', film_id: '1' },
    { _id: 7, person_id: '7', film_id: '1' },
    { _id: 8, person_id: '8', film_id: '1' },
    { _id: 9, person_id: '9', film_id: '1' },
    { _id: 10, person_id: '10', film_id: '1' },
    { _id: 11, person_id: '12', film_id: '1' },
    { _id: 12, person_id: '13', film_id: '1' },
    { _id: 13, person_id: '14', film_id: '1' },
    { _id: 14, person_id: '15', film_id: '1' },
    { _id: 15, person_id: '16', film_id: '1' },
    { _id: 16, person_id: '18', film_id: '1' },
    { _id: 17, person_id: '19', film_id: '1' },
    { _id: 18, person_id: '81', film_id: '1' },
    { _id: 19, person_id: '2', film_id: '5' },
    { _id: 20, person_id: '3', film_id: '5' },
    { _id: 21, person_id: '6', film_id: '5' },
    { _id: 22, person_id: '7', film_id: '5' },
    { _id: 23, person_id: '10', film_id: '5' },
    { _id: 24, person_id: '11', film_id: '5' },
    { _id: 25, person_id: '20', film_id: '5' },
    { _id: 26, person_id: '21', film_id: '5' },
    { _id: 27, person_id: '22', film_id: '5' },
    { _id: 28, person_id: '33', film_id: '5' },
    { _id: 29, person_id: '36', film_id: '5' },
    { _id: 30, person_id: '40', film_id: '5' },
    { _id: 31, person_id: '43', film_id: '5' },
    { _id: 32, person_id: '46', film_id: '5' },
    { _id: 33, person_id: '51', film_id: '5' },
    { _id: 34, person_id: '52', film_id: '5' },
    { _id: 35, person_id: '53', film_id: '5' },
    { _id: 36, person_id: '58', film_id: '5' },
    { _id: 37, person_id: '59', film_id: '5' },
    { _id: 38, person_id: '60', film_id: '5' },
    { _id: 39, person_id: '61', film_id: '5' },
    { _id: 40, person_id: '62', film_id: '5' },
    { _id: 41, person_id: '63', film_id: '5' },
    { _id: 42, person_id: '64', film_id: '5' },
    { _id: 43, person_id: '65', film_id: '5' },
    { _id: 44, person_id: '66', film_id: '5' },
    { _id: 45, person_id: '67', film_id: '5' },
    { _id: 46, person_id: '68', film_id: '5' },
    { _id: 47, person_id: '69', film_id: '5' },
    { _id: 48, person_id: '70', film_id: '5' },
    { _id: 49, person_id: '71', film_id: '5' },
    { _id: 50, person_id: '72', film_id: '5' },
    { _id: 51, person_id: '73', film_id: '5' },
    { _id: 52, person_id: '74', film_id: '5' },
    { _id: 53, person_id: '75', film_id: '5' },
    { _id: 54, person_id: '76', film_id: '5' },
    { _id: 55, person_id: '77', film_id: '5' },
    { _id: 56, person_id: '78', film_id: '5' },
    { _id: 57, person_id: '82', film_id: '5' },
    { _id: 58, person_id: '35', film_id: '5' },
    { _id: 59, person_id: '2', film_id: '4' },
    { _id: 60, person_id: '3', film_id: '4' },
    { _id: 61, person_id: '10', film_id: '4' },
    { _id: 62, person_id: '11', film_id: '4' },
    { _id: 63, person_id: '16', film_id: '4' },
    { _id: 64, person_id: '20', film_id: '4' },
    { _id: 65, person_id: '21', film_id: '4' },
    { _id: 66, person_id: '32', film_id: '4' },
    { _id: 67, person_id: '33', film_id: '4' },
    { _id: 68, person_id: '34', film_id: '4' },
    { _id: 69, person_id: '36', film_id: '4' },
    { _id: 70, person_id: '37', film_id: '4' },
    { _id: 71, person_id: '38', film_id: '4' },
    { _id: 72, person_id: '39', film_id: '4' },
    { _id: 73, person_id: '40', film_id: '4' },
    { _id: 74, person_id: '41', film_id: '4' },
    { _id: 75, person_id: '42', film_id: '4' },
    { _id: 76, person_id: '43', film_id: '4' },
    { _id: 77, person_id: '44', film_id: '4' },
    { _id: 78, person_id: '46', film_id: '4' },
    { _id: 79, person_id: '48', film_id: '4' },
    { _id: 80, person_id: '49', film_id: '4' },
    { _id: 81, person_id: '50', film_id: '4' },
    { _id: 82, person_id: '51', film_id: '4' },
    { _id: 83, person_id: '52', film_id: '4' },
    { _id: 84, person_id: '53', film_id: '4' },
    { _id: 85, person_id: '54', film_id: '4' },
    { _id: 86, person_id: '55', film_id: '4' },
    { _id: 87, person_id: '56', film_id: '4' },
    { _id: 88, person_id: '57', film_id: '4' },
    { _id: 89, person_id: '58', film_id: '4' },
    { _id: 90, person_id: '59', film_id: '4' },
    { _id: 91, person_id: '47', film_id: '4' },
    { _id: 92, person_id: '35', film_id: '4' },
    { _id: 93, person_id: '1', film_id: '6' },
    { _id: 94, person_id: '2', film_id: '6' },
    { _id: 95, person_id: '3', film_id: '6' },
    { _id: 96, person_id: '4', film_id: '6' },
    { _id: 97, person_id: '5', film_id: '6' },
    { _id: 98, person_id: '6', film_id: '6' },
    { _id: 99, person_id: '7', film_id: '6' },
    { _id: 100, person_id: '10', film_id: '6' },
    { _id: 101, person_id: '11', film_id: '6' },
    { _id: 102, person_id: '12', film_id: '6' },
    { _id: 103, person_id: '13', film_id: '6' },
    { _id: 104, person_id: '20', film_id: '6' },
    { _id: 105, person_id: '21', film_id: '6' },
    { _id: 106, person_id: '33', film_id: '6' },
    { _id: 107, person_id: '46', film_id: '6' },
    { _id: 108, person_id: '51', film_id: '6' },
    { _id: 109, person_id: '52', film_id: '6' },
    { _id: 110, person_id: '53', film_id: '6' },
    { _id: 111, person_id: '54', film_id: '6' },
    { _id: 112, person_id: '55', film_id: '6' },
    { _id: 113, person_id: '56', film_id: '6' },
    { _id: 114, person_id: '58', film_id: '6' },
    { _id: 115, person_id: '63', film_id: '6' },
    { _id: 116, person_id: '64', film_id: '6' },
    { _id: 117, person_id: '67', film_id: '6' },
    { _id: 118, person_id: '68', film_id: '6' },
    { _id: 119, person_id: '75', film_id: '6' },
    { _id: 120, person_id: '78', film_id: '6' },
    { _id: 121, person_id: '79', film_id: '6' },
    { _id: 122, person_id: '80', film_id: '6' },
    { _id: 123, person_id: '81', film_id: '6' },
    { _id: 124, person_id: '82', film_id: '6' },
    { _id: 125, person_id: '83', film_id: '6' },
    { _id: 126, person_id: '35', film_id: '6' },
    { _id: 127, person_id: '1', film_id: '3' },
    { _id: 128, person_id: '2', film_id: '3' },
    { _id: 129, person_id: '3', film_id: '3' },
    { _id: 130, person_id: '4', film_id: '3' },
    { _id: 131, person_id: '5', film_id: '3' },
    { _id: 132, person_id: '10', film_id: '3' },
    { _id: 133, person_id: '13', film_id: '3' },
    { _id: 134, person_id: '14', film_id: '3' },
    { _id: 135, person_id: '16', film_id: '3' },
    { _id: 136, person_id: '18', film_id: '3' },
    { _id: 137, person_id: '20', film_id: '3' },
    { _id: 138, person_id: '21', film_id: '3' },
    { _id: 139, person_id: '22', film_id: '3' },
    { _id: 140, person_id: '25', film_id: '3' },
    { _id: 141, person_id: '27', film_id: '3' },
    { _id: 142, person_id: '28', film_id: '3' },
    { _id: 143, person_id: '29', film_id: '3' },
    { _id: 144, person_id: '30', film_id: '3' },
    { _id: 145, person_id: '31', film_id: '3' },
    { _id: 146, person_id: '45', film_id: '3' },
    { _id: 147, person_id: '1', film_id: '2' },
    { _id: 148, person_id: '2', film_id: '2' },
    { _id: 149, person_id: '3', film_id: '2' },
    { _id: 150, person_id: '4', film_id: '2' },
    { _id: 151, person_id: '5', film_id: '2' },
    { _id: 152, person_id: '10', film_id: '2' },
    { _id: 153, person_id: '13', film_id: '2' },
    { _id: 154, person_id: '14', film_id: '2' },
    { _id: 155, person_id: '18', film_id: '2' },
    { _id: 156, person_id: '20', film_id: '2' },
    { _id: 157, person_id: '21', film_id: '2' },
    { _id: 158, person_id: '22', film_id: '2' },
    { _id: 159, person_id: '23', film_id: '2' },
    { _id: 160, person_id: '24', film_id: '2' },
    { _id: 161, person_id: '25', film_id: '2' },
    { _id: 162, person_id: '26', film_id: '2' },
    { _id: 163, person_id: '1', film_id: '7' },
    { _id: 164, person_id: '3', film_id: '7' },
    { _id: 165, person_id: '5', film_id: '7' },
    { _id: 166, person_id: '13', film_id: '7' },
    { _id: 167, person_id: '14', film_id: '7' },
    { _id: 168, person_id: '27', film_id: '7' },
    { _id: 169, person_id: '84', film_id: '7' },
    { _id: 170, person_id: '85', film_id: '7' },
    { _id: 171, person_id: '86', film_id: '7' },
    { _id: 172, person_id: '87', film_id: '7' },
    { _id: 173, person_id: '88', film_id: '7' },
  ],
  'public.films': [
    {
      _id: 1,
      title: 'A New Hope',
      episode_id: 4,
      opening_crawl:
        "It is a period of civil war.\nRebel spaceships, striking\nfrom a hidden base, have won\ntheir first victory against\nthe evil Galactic Empire.\n\nDuring the battle, Rebel\nspies managed to steal secret\nplans to the Empire''s\nultimate weapon, the DEATH\nSTAR, an armored space\nstation with enough power\nto destroy an entire planet.\n\nPursued by the Empire''s\nsinister agents, Princess\nLeia races home aboard her\nstarship, custodian of the\nstolen plans that can save her\npeople and restore\nfreedom to the galaxy....",
      director: 'George Lucas',
      producer: 'Gary Kurtz, Rick McCallum',
      release_date: '1977-05-25T04:00:00.000Z',
    },
    {
      _id: 5,
      title: 'Attack of the Clones',
      episode_id: 2,
      opening_crawl:
        'There is unrest in the Galactic\nSenate. Several thousand solar\nsystems have declared their\nintentions to leave the Republic.\n\nThis separatist movement,\nunder the leadership of the\nmysterious Count Dooku, has\nmade it difficult for the limited\nnumber of Jedi Knights to maintain \npeace and order in the galaxy.\n\nSenator Amidala, the former\nQueen of Naboo, is returning\nto the Galactic Senate to vote\non the critical issue of creating\nan ARMY OF THE REPUBLIC\nto assist the overwhelmed\nJedi....',
      director: 'George Lucas',
      producer: 'Rick McCallum',
      release_date: '2002-05-16T04:00:00.000Z',
    },
    {
      _id: 4,
      title: 'The Phantom Menace',
      episode_id: 1,
      opening_crawl:
        'Turmoil has engulfed the\nGalactic Republic. The taxation\nof trade routes to outlying star\nsystems is in dispute.\n\nHoping to resolve the matter\nwith a blockade of deadly\nbattleships, the greedy Trade\nFederation has stopped all\nshipping to the small planet\nof Naboo.\n\nWhile the Congress of the\nRepublic endlessly debates\nthis alarming chain of events,\nthe Supreme Chancellor has\nsecretly dispatched two Jedi\nKnights, the guardians of\npeace and justice in the\ngalaxy, to settle the conflict....',
      director: 'George Lucas',
      producer: 'Rick McCallum',
      release_date: '1999-05-19T04:00:00.000Z',
    },
    {
      _id: 6,
      title: 'Revenge of the Sith',
      episode_id: 3,
      opening_crawl:
        'War! The Republic is crumbling\nunder attacks by the ruthless\nSith Lord, Count Dooku.\nThere are heroes on both sides.\nEvil is everywhere.\n\nIn a stunning move, the\nfiendish droid leader, General\nGrievous, has swept into the\nRepublic capital and kidnapped\nChancellor Palpatine, leader of\nthe Galactic Senate.\n\nAs the Separatist Droid Army\nattempts to flee the besieged\ncapital with their valuable\nhostage, two Jedi Knights lead a\ndesperate mission to rescue the\ncaptive Chancellor....',
      director: 'George Lucas',
      producer: 'Rick McCallum',
      release_date: '2005-05-19T04:00:00.000Z',
    },
    {
      _id: 3,
      title: 'Return of the Jedi',
      episode_id: 6,
      opening_crawl:
        'Luke Skywalker has returned to\nhis home planet of Tatooine in\nan attempt to rescue his\nfriend Han Solo from the\nclutches of the vile gangster\nJabba the Hutt.\n\nLittle does Luke know that the\nGALACTIC EMPIRE has secretly\nbegun construction on a new\narmored space station even\nmore powerful than the first\ndreaded Death Star.\n\nWhen completed, this ultimate\nweapon will spell certain doom\nfor the small band of rebels\nstruggling to restore freedom\nto the galaxy...',
      director: 'Richard Marquand',
      producer: 'Howard G. Kazanjian, George Lucas, Rick McCallum',
      release_date: '1983-05-25T04:00:00.000Z',
    },
    {
      _id: 2,
      title: 'The Empire Strikes Back',
      episode_id: 5,
      opening_crawl:
        'It is a dark time for the\nRebellion. Although the Death\nStar has been destroyed,\nImperial troops have driven the\nRebel forces from their hidden\nbase and pursued them across\nthe galaxy.\n\nEvading the dreaded Imperial\nStarfleet, a group of freedom\nfighters led by Luke Skywalker\nhas established a new secret\nbase on the remote ice world\nof Hoth.\n\nThe evil lord Darth Vader,\nobsessed with finding young\nSkywalker, has dispatched\nthousands of remote probes into\nthe far reaches of space....',
      director: 'Irvin Kershner',
      producer: 'Gary Kurtz, Rick McCallum',
      release_date: '1980-05-17T04:00:00.000Z',
    },
    {
      _id: 7,
      title: 'The Force Awakens',
      episode_id: 7,
      opening_crawl:
        "Luke Skywalker has vanished.\nIn his absence, the sinister\nFIRST ORDER has risen from\nthe ashes of the Empire\nand will not rest until\nSkywalker, the last Jedi,\nhas been destroyed.\n \nWith the support of the\nREPUBLIC, General Leia Organa\nleads a brave RESISTANCE.\nShe is desperate to find her\nbrother Luke and gain his\nhelp in restoring peace and\njustice to the galaxy.\n \nLeia has sent her most daring\npilot on a secret mission\nto Jakku, where an old ally\nhas discovered a clue to\nLuke''s whereabouts....",
      director: 'J. J. Abrams',
      producer: 'Kathleen Kennedy, J. J. Abrams, Bryan Burk',
      release_date: '2015-12-11T05:00:00.000Z',
    },
  ],
  'public.people': [
    {
      _id: 1,
      name: 'Luke Skywalker',
      mass: '77',
      hair_color: 'blond',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: '19BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '1',
      height: 172,
    },
    {
      _id: 2,
      name: 'C-3PO',
      mass: '75',
      hair_color: 'n/a',
      skin_color: 'gold',
      eye_color: 'yellow',
      birth_year: '112BBY',
      gender: 'n/a',
      species_id: '2',
      homeworld_id: '1',
      height: 167,
    },
    {
      _id: 3,
      name: 'R2-D2',
      mass: '32',
      hair_color: 'n/a',
      skin_color: 'white, blue',
      eye_color: 'red',
      birth_year: '33BBY',
      gender: 'n/a',
      species_id: '2',
      homeworld_id: '8',
      height: 96,
    },
    {
      _id: 4,
      name: 'Darth Vader',
      mass: '136',
      hair_color: 'none',
      skin_color: 'white',
      eye_color: 'yellow',
      birth_year: '41.9BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '1',
      height: 202,
    },
    {
      _id: 5,
      name: 'Leia Organa',
      mass: '49',
      hair_color: 'brown',
      skin_color: 'light',
      eye_color: 'brown',
      birth_year: '19BBY',
      gender: 'female',
      species_id: '1',
      homeworld_id: '2',
      height: 150,
    },
    {
      _id: 6,
      name: 'Owen Lars',
      mass: '120',
      hair_color: 'brown, grey',
      skin_color: 'light',
      eye_color: 'blue',
      birth_year: '52BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '1',
      height: 178,
    },
    {
      _id: 7,
      name: 'Beru Whitesun lars',
      mass: '75',
      hair_color: 'brown',
      skin_color: 'light',
      eye_color: 'blue',
      birth_year: '47BBY',
      gender: 'female',
      species_id: '1',
      homeworld_id: '1',
      height: 165,
    },
    {
      _id: 8,
      name: 'R5-D4',
      mass: '32',
      hair_color: 'n/a',
      skin_color: 'white, red',
      eye_color: 'red',
      birth_year: null,
      gender: 'n/a',
      species_id: '2',
      homeworld_id: '1',
      height: 97,
    },
    {
      _id: 9,
      name: 'Biggs Darklighter',
      mass: '84',
      hair_color: 'black',
      skin_color: 'light',
      eye_color: 'brown',
      birth_year: '24BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '1',
      height: 183,
    },
    {
      _id: 10,
      name: 'Obi-Wan Kenobi',
      mass: '77',
      hair_color: 'auburn, white',
      skin_color: 'fair',
      eye_color: 'blue-gray',
      birth_year: '57BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '20',
      height: 182,
    },
    {
      _id: 11,
      name: 'Anakin Skywalker',
      mass: '84',
      hair_color: 'blond',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: '41.9BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '1',
      height: 188,
    },
    {
      _id: 12,
      name: 'Wilhuff Tarkin',
      mass: null,
      hair_color: 'auburn, grey',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: '64BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '21',
      height: 180,
    },
    {
      _id: 13,
      name: 'Chewbacca',
      mass: '112',
      hair_color: 'brown',
      skin_color: null,
      eye_color: 'blue',
      birth_year: '200BBY',
      gender: 'male',
      species_id: '3',
      homeworld_id: '14',
      height: 228,
    },
    {
      _id: 14,
      name: 'Han Solo',
      mass: '80',
      hair_color: 'brown',
      skin_color: 'fair',
      eye_color: 'brown',
      birth_year: '29BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '22',
      height: 180,
    },
    {
      _id: 15,
      name: 'Greedo',
      mass: '74',
      hair_color: 'n/a',
      skin_color: 'green',
      eye_color: 'black',
      birth_year: '44BBY',
      gender: 'male',
      species_id: '4',
      homeworld_id: '23',
      height: 173,
    },
    {
      _id: 16,
      name: 'Jabba Desilijic Tiure',
      mass: '1,358',
      hair_color: 'n/a',
      skin_color: 'green-tan, brown',
      eye_color: 'orange',
      birth_year: '600BBY',
      gender: 'hermaphrodite',
      species_id: '5',
      homeworld_id: '24',
      height: 175,
    },
    {
      _id: 18,
      name: 'Wedge Antilles',
      mass: '77',
      hair_color: 'brown',
      skin_color: 'fair',
      eye_color: 'hazel',
      birth_year: '21BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '22',
      height: 170,
    },
    {
      _id: 19,
      name: 'Jek Tono Porkins',
      mass: '110',
      hair_color: 'brown',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: null,
      gender: 'male',
      species_id: '1',
      homeworld_id: '26',
      height: 180,
    },
    {
      _id: 20,
      name: 'Yoda',
      mass: '17',
      hair_color: 'white',
      skin_color: 'green',
      eye_color: 'brown',
      birth_year: '896BBY',
      gender: 'male',
      species_id: '6',
      homeworld_id: '28',
      height: 66,
    },
    {
      _id: 21,
      name: 'Palpatine',
      mass: '75',
      hair_color: 'grey',
      skin_color: 'pale',
      eye_color: 'yellow',
      birth_year: '82BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '8',
      height: 170,
    },
    {
      _id: 22,
      name: 'Boba Fett',
      mass: '78.2',
      hair_color: 'black',
      skin_color: 'fair',
      eye_color: 'brown',
      birth_year: '31.5BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '10',
      height: 183,
    },
    {
      _id: 23,
      name: 'IG-88',
      mass: '140',
      hair_color: 'none',
      skin_color: 'metal',
      eye_color: 'red',
      birth_year: '15BBY',
      gender: 'none',
      species_id: '2',
      homeworld_id: '28',
      height: 200,
    },
    {
      _id: 24,
      name: 'Bossk',
      mass: '113',
      hair_color: 'none',
      skin_color: 'green',
      eye_color: 'red',
      birth_year: '53BBY',
      gender: 'male',
      species_id: '7',
      homeworld_id: '29',
      height: 190,
    },
    {
      _id: 25,
      name: 'Lando Calrissian',
      mass: '79',
      hair_color: 'black',
      skin_color: 'dark',
      eye_color: 'brown',
      birth_year: '31BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '30',
      height: 177,
    },
    {
      _id: 26,
      name: 'Lobot',
      mass: '79',
      hair_color: 'none',
      skin_color: 'light',
      eye_color: 'blue',
      birth_year: '37BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '6',
      height: 175,
    },
    {
      _id: 27,
      name: 'Ackbar',
      mass: '83',
      hair_color: 'none',
      skin_color: 'brown mottle',
      eye_color: 'orange',
      birth_year: '41BBY',
      gender: 'male',
      species_id: '8',
      homeworld_id: '31',
      height: 180,
    },
    {
      _id: 28,
      name: 'Mon Mothma',
      mass: null,
      hair_color: 'auburn',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: '48BBY',
      gender: 'female',
      species_id: '1',
      homeworld_id: '32',
      height: 150,
    },
    {
      _id: 29,
      name: 'Arvel Crynyd',
      mass: null,
      hair_color: 'brown',
      skin_color: 'fair',
      eye_color: 'brown',
      birth_year: null,
      gender: 'male',
      species_id: '1',
      homeworld_id: '28',
      height: null,
    },
    {
      _id: 30,
      name: 'Wicket Systri Warrick',
      mass: '20',
      hair_color: 'brown',
      skin_color: 'brown',
      eye_color: 'brown',
      birth_year: '8BBY',
      gender: 'male',
      species_id: '9',
      homeworld_id: '7',
      height: 88,
    },
    {
      _id: 31,
      name: 'Nien Nunb',
      mass: '68',
      hair_color: 'none',
      skin_color: 'grey',
      eye_color: 'black',
      birth_year: null,
      gender: 'male',
      species_id: '10',
      homeworld_id: '33',
      height: 160,
    },
    {
      _id: 32,
      name: 'Qui-Gon Jinn',
      mass: '89',
      hair_color: 'brown',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: '92BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '28',
      height: 193,
    },
    {
      _id: 33,
      name: 'Nute Gunray',
      mass: '90',
      hair_color: 'none',
      skin_color: 'mottled green',
      eye_color: 'red',
      birth_year: null,
      gender: 'male',
      species_id: '11',
      homeworld_id: '18',
      height: 191,
    },
    {
      _id: 34,
      name: 'Finis Valorum',
      mass: null,
      hair_color: 'blond',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: '91BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '9',
      height: 170,
    },
    {
      _id: 36,
      name: 'Jar Jar Binks',
      mass: '66',
      hair_color: 'none',
      skin_color: 'orange',
      eye_color: 'orange',
      birth_year: '52BBY',
      gender: 'male',
      species_id: '12',
      homeworld_id: '8',
      height: 196,
    },
    {
      _id: 37,
      name: 'Roos Tarpals',
      mass: '82',
      hair_color: 'none',
      skin_color: 'grey',
      eye_color: 'orange',
      birth_year: null,
      gender: 'male',
      species_id: '12',
      homeworld_id: '8',
      height: 224,
    },
    {
      _id: 38,
      name: 'Rugor Nass',
      mass: null,
      hair_color: 'none',
      skin_color: 'green',
      eye_color: 'orange',
      birth_year: null,
      gender: 'male',
      species_id: '12',
      homeworld_id: '8',
      height: 206,
    },
    {
      _id: 39,
      name: 'Ric Olié',
      mass: null,
      hair_color: 'brown',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: null,
      gender: 'male',
      species_id: null,
      homeworld_id: '8',
      height: 183,
    },
    {
      _id: 40,
      name: 'Watto',
      mass: null,
      hair_color: 'black',
      skin_color: 'blue, grey',
      eye_color: 'yellow',
      birth_year: null,
      gender: 'male',
      species_id: '13',
      homeworld_id: '34',
      height: 137,
    },
    {
      _id: 41,
      name: 'Sebulba',
      mass: '40',
      hair_color: 'none',
      skin_color: 'grey, red',
      eye_color: 'orange',
      birth_year: null,
      gender: 'male',
      species_id: '14',
      homeworld_id: '35',
      height: 112,
    },
    {
      _id: 42,
      name: 'Quarsh Panaka',
      mass: null,
      hair_color: 'black',
      skin_color: 'dark',
      eye_color: 'brown',
      birth_year: '62BBY',
      gender: 'male',
      species_id: null,
      homeworld_id: '8',
      height: 183,
    },
    {
      _id: 43,
      name: 'Shmi Skywalker',
      mass: null,
      hair_color: 'black',
      skin_color: 'fair',
      eye_color: 'brown',
      birth_year: '72BBY',
      gender: 'female',
      species_id: '1',
      homeworld_id: '1',
      height: 163,
    },
    {
      _id: 44,
      name: 'Darth Maul',
      mass: '80',
      hair_color: 'none',
      skin_color: 'red',
      eye_color: 'yellow',
      birth_year: '54BBY',
      gender: 'male',
      species_id: '22',
      homeworld_id: '36',
      height: 175,
    },
    {
      _id: 45,
      name: 'Bib Fortuna',
      mass: null,
      hair_color: 'none',
      skin_color: 'pale',
      eye_color: 'pink',
      birth_year: null,
      gender: 'male',
      species_id: '15',
      homeworld_id: '37',
      height: 180,
    },
    {
      _id: 46,
      name: 'Ayla Secura',
      mass: '55',
      hair_color: 'none',
      skin_color: 'blue',
      eye_color: 'hazel',
      birth_year: '48BBY',
      gender: 'female',
      species_id: '15',
      homeworld_id: '37',
      height: 178,
    },
    {
      _id: 48,
      name: 'Dud Bolt',
      mass: '45',
      hair_color: 'none',
      skin_color: 'blue, grey',
      eye_color: 'yellow',
      birth_year: null,
      gender: 'male',
      species_id: '17',
      homeworld_id: '39',
      height: 94,
    },
    {
      _id: 49,
      name: 'Gasgano',
      mass: null,
      hair_color: 'none',
      skin_color: 'white, blue',
      eye_color: 'black',
      birth_year: null,
      gender: 'male',
      species_id: '18',
      homeworld_id: '40',
      height: 122,
    },
    {
      _id: 50,
      name: 'Ben Quadinaros',
      mass: '65',
      hair_color: 'none',
      skin_color: 'grey, green, yellow',
      eye_color: 'orange',
      birth_year: null,
      gender: 'male',
      species_id: '19',
      homeworld_id: '41',
      height: 163,
    },
    {
      _id: 51,
      name: 'Mace Windu',
      mass: '84',
      hair_color: 'none',
      skin_color: 'dark',
      eye_color: 'brown',
      birth_year: '72BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '42',
      height: 188,
    },
    {
      _id: 52,
      name: 'Ki-Adi-Mundi',
      mass: '82',
      hair_color: 'white',
      skin_color: 'pale',
      eye_color: 'yellow',
      birth_year: '92BBY',
      gender: 'male',
      species_id: '20',
      homeworld_id: '43',
      height: 198,
    },
    {
      _id: 53,
      name: 'Kit Fisto',
      mass: '87',
      hair_color: 'none',
      skin_color: 'green',
      eye_color: 'black',
      birth_year: null,
      gender: 'male',
      species_id: '21',
      homeworld_id: '44',
      height: 196,
    },
    {
      _id: 54,
      name: 'Eeth Koth',
      mass: null,
      hair_color: 'black',
      skin_color: 'brown',
      eye_color: 'brown',
      birth_year: null,
      gender: 'male',
      species_id: '22',
      homeworld_id: '45',
      height: 171,
    },
    {
      _id: 55,
      name: 'Adi Gallia',
      mass: '50',
      hair_color: 'none',
      skin_color: 'dark',
      eye_color: 'blue',
      birth_year: null,
      gender: 'female',
      species_id: '23',
      homeworld_id: '9',
      height: 184,
    },
    {
      _id: 56,
      name: 'Saesee Tiin',
      mass: null,
      hair_color: 'none',
      skin_color: 'pale',
      eye_color: 'orange',
      birth_year: null,
      gender: 'male',
      species_id: '24',
      homeworld_id: '47',
      height: 188,
    },
    {
      _id: 57,
      name: 'Yarael Poof',
      mass: null,
      hair_color: 'none',
      skin_color: 'white',
      eye_color: 'yellow',
      birth_year: null,
      gender: 'male',
      species_id: '25',
      homeworld_id: '48',
      height: 264,
    },
    {
      _id: 58,
      name: 'Plo Koon',
      mass: '80',
      hair_color: 'none',
      skin_color: 'orange',
      eye_color: 'black',
      birth_year: '22BBY',
      gender: 'male',
      species_id: '26',
      homeworld_id: '49',
      height: 188,
    },
    {
      _id: 59,
      name: 'Mas Amedda',
      mass: null,
      hair_color: 'none',
      skin_color: 'blue',
      eye_color: 'blue',
      birth_year: null,
      gender: 'male',
      species_id: '27',
      homeworld_id: '50',
      height: 196,
    },
    {
      _id: 60,
      name: 'Gregar Typho',
      mass: '85',
      hair_color: 'black',
      skin_color: 'dark',
      eye_color: 'brown',
      birth_year: null,
      gender: 'male',
      species_id: '1',
      homeworld_id: '8',
      height: 185,
    },
    {
      _id: 61,
      name: 'Cordé',
      mass: null,
      hair_color: 'brown',
      skin_color: 'light',
      eye_color: 'brown',
      birth_year: null,
      gender: 'female',
      species_id: '1',
      homeworld_id: '8',
      height: 157,
    },
    {
      _id: 62,
      name: 'Cliegg Lars',
      mass: null,
      hair_color: 'brown',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: '82BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '1',
      height: 183,
    },
    {
      _id: 63,
      name: 'Poggle the Lesser',
      mass: '80',
      hair_color: 'none',
      skin_color: 'green',
      eye_color: 'yellow',
      birth_year: null,
      gender: 'male',
      species_id: '28',
      homeworld_id: '11',
      height: 183,
    },
    {
      _id: 64,
      name: 'Luminara Unduli',
      mass: '56.2',
      hair_color: 'black',
      skin_color: 'yellow',
      eye_color: 'blue',
      birth_year: '58BBY',
      gender: 'female',
      species_id: '29',
      homeworld_id: '51',
      height: 170,
    },
    {
      _id: 65,
      name: 'Barriss Offee',
      mass: '50',
      hair_color: 'black',
      skin_color: 'yellow',
      eye_color: 'blue',
      birth_year: '40BBY',
      gender: 'female',
      species_id: '29',
      homeworld_id: '51',
      height: 166,
    },
    {
      _id: 66,
      name: 'Dormé',
      mass: null,
      hair_color: 'brown',
      skin_color: 'light',
      eye_color: 'brown',
      birth_year: null,
      gender: 'female',
      species_id: '1',
      homeworld_id: '8',
      height: 165,
    },
    {
      _id: 67,
      name: 'Dooku',
      mass: '80',
      hair_color: 'white',
      skin_color: 'fair',
      eye_color: 'brown',
      birth_year: '102BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '52',
      height: 193,
    },
    {
      _id: 68,
      name: 'Bail Prestor Organa',
      mass: null,
      hair_color: 'black',
      skin_color: 'tan',
      eye_color: 'brown',
      birth_year: '67BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '2',
      height: 191,
    },
    {
      _id: 69,
      name: 'Jango Fett',
      mass: '79',
      hair_color: 'black',
      skin_color: 'tan',
      eye_color: 'brown',
      birth_year: '66BBY',
      gender: 'male',
      species_id: '1',
      homeworld_id: '53',
      height: 183,
    },
    {
      _id: 70,
      name: 'Zam Wesell',
      mass: '55',
      hair_color: 'blonde',
      skin_color: 'fair, green, yellow',
      eye_color: 'yellow',
      birth_year: null,
      gender: 'female',
      species_id: '30',
      homeworld_id: '54',
      height: 168,
    },
    {
      _id: 71,
      name: 'Dexter Jettster',
      mass: '102',
      hair_color: 'none',
      skin_color: 'brown',
      eye_color: 'yellow',
      birth_year: null,
      gender: 'male',
      species_id: '31',
      homeworld_id: '55',
      height: 198,
    },
    {
      _id: 72,
      name: 'Lama Su',
      mass: '88',
      hair_color: 'none',
      skin_color: 'grey',
      eye_color: 'black',
      birth_year: null,
      gender: 'male',
      species_id: '32',
      homeworld_id: '10',
      height: 229,
    },
    {
      _id: 73,
      name: 'Taun We',
      mass: null,
      hair_color: 'none',
      skin_color: 'grey',
      eye_color: 'black',
      birth_year: null,
      gender: 'female',
      species_id: '32',
      homeworld_id: '10',
      height: 213,
    },
    {
      _id: 74,
      name: 'Jocasta Nu',
      mass: null,
      hair_color: 'white',
      skin_color: 'fair',
      eye_color: 'blue',
      birth_year: null,
      gender: 'female',
      species_id: '1',
      homeworld_id: '9',
      height: 167,
    },
    {
      _id: 47,
      name: 'Ratts Tyerell',
      mass: '15',
      hair_color: 'none',
      skin_color: 'grey, blue',
      eye_color: null,
      birth_year: null,
      gender: 'male',
      species_id: '16',
      homeworld_id: '38',
      height: 79,
    },
    {
      _id: 75,
      name: 'R4-P17',
      mass: null,
      hair_color: 'none',
      skin_color: 'silver, red',
      eye_color: 'red, blue',
      birth_year: null,
      gender: 'female',
      species_id: null,
      homeworld_id: '28',
      height: 96,
    },
    {
      _id: 76,
      name: 'Wat Tambor',
      mass: '48',
      hair_color: 'none',
      skin_color: 'green, grey',
      eye_color: null,
      birth_year: null,
      gender: 'male',
      species_id: '33',
      homeworld_id: '56',
      height: 193,
    },
    {
      _id: 77,
      name: 'San Hill',
      mass: null,
      hair_color: 'none',
      skin_color: 'grey',
      eye_color: 'gold',
      birth_year: null,
      gender: 'male',
      species_id: '34',
      homeworld_id: '57',
      height: 191,
    },
    {
      _id: 78,
      name: 'Shaak Ti',
      mass: '57',
      hair_color: 'none',
      skin_color: 'red, blue, white',
      eye_color: 'black',
      birth_year: null,
      gender: 'female',
      species_id: '35',
      homeworld_id: '58',
      height: 178,
    },
    {
      _id: 79,
      name: 'Grievous',
      mass: '159',
      hair_color: 'none',
      skin_color: 'brown, white',
      eye_color: 'green, yellow',
      birth_year: null,
      gender: 'male',
      species_id: '36',
      homeworld_id: '59',
      height: 216,
    },
    {
      _id: 80,
      name: 'Tarfful',
      mass: '136',
      hair_color: 'brown',
      skin_color: 'brown',
      eye_color: 'blue',
      birth_year: null,
      gender: 'male',
      species_id: '3',
      homeworld_id: '14',
      height: 234,
    },
    {
      _id: 81,
      name: 'Raymus Antilles',
      mass: '79',
      hair_color: 'brown',
      skin_color: 'light',
      eye_color: 'brown',
      birth_year: null,
      gender: 'male',
      species_id: '1',
      homeworld_id: '2',
      height: 188,
    },
    {
      _id: 82,
      name: 'Sly Moore',
      mass: '48',
      hair_color: 'none',
      skin_color: 'pale',
      eye_color: 'white',
      birth_year: null,
      gender: 'female',
      species_id: null,
      homeworld_id: '60',
      height: 178,
    },
    {
      _id: 83,
      name: 'Tion Medon',
      mass: '80',
      hair_color: 'none',
      skin_color: 'grey',
      eye_color: 'black',
      birth_year: null,
      gender: 'male',
      species_id: '37',
      homeworld_id: '12',
      height: 206,
    },
    {
      _id: 84,
      name: 'Finn',
      mass: null,
      hair_color: 'black',
      skin_color: 'dark',
      eye_color: 'dark',
      birth_year: null,
      gender: 'male',
      species_id: '1',
      homeworld_id: '28',
      height: null,
    },
    {
      _id: 85,
      name: 'Rey',
      mass: null,
      hair_color: 'brown',
      skin_color: 'light',
      eye_color: 'hazel',
      birth_year: null,
      gender: 'female',
      species_id: '1',
      homeworld_id: '28',
      height: null,
    },
    {
      _id: 86,
      name: 'Poe Dameron',
      mass: null,
      hair_color: 'brown',
      skin_color: 'light',
      eye_color: 'brown',
      birth_year: null,
      gender: 'male',
      species_id: '1',
      homeworld_id: '28',
      height: null,
    },
    {
      _id: 87,
      name: 'BB8',
      mass: null,
      hair_color: 'none',
      skin_color: 'none',
      eye_color: 'black',
      birth_year: null,
      gender: 'none',
      species_id: '2',
      homeworld_id: '28',
      height: null,
    },
    {
      _id: 88,
      name: 'Captain Phasma',
      mass: null,
      hair_color: null,
      skin_color: null,
      eye_color: null,
      birth_year: null,
      gender: 'female',
      species_id: '1',
      homeworld_id: '28',
      height: null,
    },
    {
      _id: 35,
      name: 'Padmé Amidala',
      mass: '45',
      hair_color: 'brown',
      skin_color: 'light',
      eye_color: 'brown',
      birth_year: '46BBY',
      gender: 'female',
      species_id: '1',
      homeworld_id: '8',
      height: 165,
    },
    {
      _id: 89,
      name: 'Stan',
      mass: null,
      hair_color: null,
      skin_color: null,
      eye_color: null,
      birth_year: null,
      gender: null,
      species_id: null,
      homeworld_id: null,
      height: null,
    },
  ],
  'public.species_in_films': [
    { _id: 1, film_id: '1', species_id: '5' },
    { _id: 2, film_id: '1', species_id: '3' },
    { _id: 3, film_id: '1', species_id: '2' },
    { _id: 4, film_id: '1', species_id: '1' },
    { _id: 5, film_id: '1', species_id: '4' },
    { _id: 6, film_id: '5', species_id: '32' },
    { _id: 7, film_id: '5', species_id: '33' },
    { _id: 8, film_id: '5', species_id: '2' },
    { _id: 9, film_id: '5', species_id: '35' },
    { _id: 10, film_id: '5', species_id: '6' },
    { _id: 11, film_id: '5', species_id: '1' },
    { _id: 12, film_id: '5', species_id: '12' },
    { _id: 13, film_id: '5', species_id: '34' },
    { _id: 14, film_id: '5', species_id: '13' },
    { _id: 15, film_id: '5', species_id: '15' },
    { _id: 16, film_id: '5', species_id: '28' },
    { _id: 17, film_id: '5', species_id: '29' },
    { _id: 18, film_id: '5', species_id: '30' },
    { _id: 19, film_id: '5', species_id: '31' },
    { _id: 20, film_id: '4', species_id: '1' },
    { _id: 21, film_id: '4', species_id: '2' },
    { _id: 22, film_id: '4', species_id: '6' },
    { _id: 23, film_id: '4', species_id: '11' },
    { _id: 24, film_id: '4', species_id: '12' },
    { _id: 25, film_id: '4', species_id: '13' },
    { _id: 26, film_id: '4', species_id: '14' },
    { _id: 27, film_id: '4', species_id: '15' },
    { _id: 28, film_id: '4', species_id: '16' },
    { _id: 29, film_id: '4', species_id: '17' },
    { _id: 30, film_id: '4', species_id: '18' },
    { _id: 31, film_id: '4', species_id: '19' },
    { _id: 32, film_id: '4', species_id: '20' },
    { _id: 33, film_id: '4', species_id: '21' },
    { _id: 34, film_id: '4', species_id: '22' },
    { _id: 35, film_id: '4', species_id: '23' },
    { _id: 36, film_id: '4', species_id: '24' },
    { _id: 37, film_id: '4', species_id: '25' },
    { _id: 38, film_id: '4', species_id: '26' },
    { _id: 39, film_id: '4', species_id: '27' },
    { _id: 40, film_id: '6', species_id: '19' },
    { _id: 41, film_id: '6', species_id: '33' },
    { _id: 42, film_id: '6', species_id: '2' },
    { _id: 43, film_id: '6', species_id: '3' },
    { _id: 44, film_id: '6', species_id: '36' },
    { _id: 45, film_id: '6', species_id: '37' },
    { _id: 46, film_id: '6', species_id: '6' },
    { _id: 47, film_id: '6', species_id: '1' },
    { _id: 48, film_id: '6', species_id: '34' },
    { _id: 49, film_id: '6', species_id: '15' },
    { _id: 50, film_id: '6', species_id: '35' },
    { _id: 51, film_id: '6', species_id: '20' },
    { _id: 52, film_id: '6', species_id: '23' },
    { _id: 53, film_id: '6', species_id: '24' },
    { _id: 54, film_id: '6', species_id: '25' },
    { _id: 55, film_id: '6', species_id: '26' },
    { _id: 56, film_id: '6', species_id: '27' },
    { _id: 57, film_id: '6', species_id: '28' },
    { _id: 58, film_id: '6', species_id: '29' },
    { _id: 59, film_id: '6', species_id: '30' },
    { _id: 60, film_id: '3', species_id: '1' },
    { _id: 61, film_id: '3', species_id: '2' },
    { _id: 62, film_id: '3', species_id: '3' },
    { _id: 63, film_id: '3', species_id: '5' },
    { _id: 64, film_id: '3', species_id: '6' },
    { _id: 65, film_id: '3', species_id: '8' },
    { _id: 66, film_id: '3', species_id: '9' },
    { _id: 67, film_id: '3', species_id: '10' },
    { _id: 68, film_id: '3', species_id: '15' },
    { _id: 69, film_id: '2', species_id: '6' },
    { _id: 70, film_id: '2', species_id: '7' },
    { _id: 71, film_id: '2', species_id: '3' },
    { _id: 72, film_id: '2', species_id: '2' },
    { _id: 73, film_id: '2', species_id: '1' },
    { _id: 74, film_id: '7', species_id: '3' },
    { _id: 75, film_id: '7', species_id: '2' },
    { _id: 76, film_id: '7', species_id: '1' },
  ],
  'public.planets_in_films': [
    { _id: 1, film_id: '1', planet_id: '2' },
    { _id: 2, film_id: '1', planet_id: '3' },
    { _id: 3, film_id: '1', planet_id: '1' },
    { _id: 4, film_id: '5', planet_id: '8' },
    { _id: 5, film_id: '5', planet_id: '9' },
    { _id: 6, film_id: '5', planet_id: '10' },
    { _id: 7, film_id: '5', planet_id: '11' },
    { _id: 8, film_id: '5', planet_id: '1' },
    { _id: 9, film_id: '4', planet_id: '8' },
    { _id: 10, film_id: '4', planet_id: '9' },
    { _id: 11, film_id: '4', planet_id: '1' },
    { _id: 12, film_id: '6', planet_id: '2' },
    { _id: 13, film_id: '6', planet_id: '5' },
    { _id: 14, film_id: '6', planet_id: '8' },
    { _id: 15, film_id: '6', planet_id: '9' },
    { _id: 16, film_id: '6', planet_id: '12' },
    { _id: 17, film_id: '6', planet_id: '13' },
    { _id: 18, film_id: '6', planet_id: '14' },
    { _id: 19, film_id: '6', planet_id: '15' },
    { _id: 20, film_id: '6', planet_id: '16' },
    { _id: 21, film_id: '6', planet_id: '17' },
    { _id: 22, film_id: '6', planet_id: '18' },
    { _id: 23, film_id: '6', planet_id: '19' },
    { _id: 24, film_id: '6', planet_id: '1' },
    { _id: 25, film_id: '3', planet_id: '5' },
    { _id: 26, film_id: '3', planet_id: '7' },
    { _id: 27, film_id: '3', planet_id: '8' },
    { _id: 28, film_id: '3', planet_id: '9' },
    { _id: 29, film_id: '3', planet_id: '1' },
    { _id: 30, film_id: '2', planet_id: '4' },
    { _id: 31, film_id: '2', planet_id: '5' },
    { _id: 32, film_id: '2', planet_id: '6' },
    { _id: 33, film_id: '2', planet_id: '27' },
    { _id: 34, film_id: '7', planet_id: '61' },
  ],
  'public.pilots': [
    { _id: 1, person_id: '1', vessel_id: '14' },
    { _id: 2, person_id: '18', vessel_id: '14' },
    { _id: 3, person_id: '13', vessel_id: '19' },
    { _id: 4, person_id: '1', vessel_id: '30' },
    { _id: 5, person_id: '5', vessel_id: '30' },
    { _id: 6, person_id: '10', vessel_id: '38' },
    { _id: 7, person_id: '32', vessel_id: '38' },
    { _id: 8, person_id: '44', vessel_id: '42' },
    { _id: 9, person_id: '11', vessel_id: '44' },
    { _id: 10, person_id: '70', vessel_id: '45' },
    { _id: 11, person_id: '11', vessel_id: '46' },
    { _id: 12, person_id: '79', vessel_id: '60' },
    { _id: 13, person_id: '67', vessel_id: '55' },
    { _id: 14, person_id: '13', vessel_id: '10' },
    { _id: 15, person_id: '14', vessel_id: '10' },
    { _id: 16, person_id: '25', vessel_id: '10' },
    { _id: 17, person_id: '31', vessel_id: '10' },
    { _id: 18, person_id: '1', vessel_id: '12' },
    { _id: 19, person_id: '9', vessel_id: '12' },
    { _id: 20, person_id: '18', vessel_id: '12' },
    { _id: 21, person_id: '19', vessel_id: '12' },
    { _id: 22, person_id: '4', vessel_id: '13' },
    { _id: 23, person_id: '22', vessel_id: '21' },
    { _id: 24, person_id: '1', vessel_id: '22' },
    { _id: 25, person_id: '13', vessel_id: '22' },
    { _id: 26, person_id: '14', vessel_id: '22' },
    { _id: 27, person_id: '29', vessel_id: '28' },
    { _id: 28, person_id: '11', vessel_id: '39' },
    { _id: 29, person_id: '60', vessel_id: '39' },
    { _id: 30, person_id: '35', vessel_id: '39' },
    { _id: 31, person_id: '39', vessel_id: '40' },
    { _id: 32, person_id: '44', vessel_id: '41' },
    { _id: 33, person_id: '10', vessel_id: '48' },
    { _id: 34, person_id: '58', vessel_id: '48' },
    { _id: 35, person_id: '35', vessel_id: '49' },
    { _id: 36, person_id: '10', vessel_id: '59' },
    { _id: 37, person_id: '11', vessel_id: '59' },
    { _id: 38, person_id: '86', vessel_id: '77' },
    { _id: 39, person_id: '10', vessel_id: '64' },
    { _id: 40, person_id: '35', vessel_id: '64' },
    { _id: 41, person_id: '10', vessel_id: '65' },
    { _id: 42, person_id: '11', vessel_id: '65' },
    { _id: 43, person_id: '10', vessel_id: '74' },
    { _id: 44, person_id: '79', vessel_id: '74' },
  ],
  'public.vessels': [
    {
      _id: 4,
      name: 'Sand Crawler',
      manufacturer: 'Corellia Mining Corporation',
      model: 'Digger Crawler',
      vessel_type: 'vehicle',
      vessel_class: 'wheeled',
      cost_in_credits: '150000',
      length: '36.8',
      max_atmosphering_speed: '30',
      crew: 46,
      passengers: 30,
      cargo_capacity: '50000',
      consumables: '2 months',
    },
    {
      _id: 6,
      name: 'T-16 skyhopper',
      manufacturer: 'Incom Corporation',
      model: 'T-16 skyhopper',
      vessel_type: 'vehicle',
      vessel_class: 'repulsorcraft',
      cost_in_credits: '14500',
      length: '10.4',
      max_atmosphering_speed: '1200',
      crew: 1,
      passengers: 1,
      cargo_capacity: '50',
      consumables: '0',
    },
    {
      _id: 7,
      name: 'X-34 landspeeder',
      manufacturer: 'SoroSuub Corporation',
      model: 'X-34 landspeeder',
      vessel_type: 'vehicle',
      vessel_class: 'repulsorcraft',
      cost_in_credits: '10550',
      length: '3.4',
      max_atmosphering_speed: '250',
      crew: 1,
      passengers: 1,
      cargo_capacity: '5',
      consumables: null,
    },
    {
      _id: 8,
      name: 'TIE/LN starfighter',
      manufacturer: 'Sienar Fleet Systems',
      model: 'Twin Ion Engine/Ln Starfighter',
      vessel_type: 'vehicle',
      vessel_class: 'starfighter',
      cost_in_credits: null,
      length: '6.4',
      max_atmosphering_speed: '1200',
      crew: 1,
      passengers: 0,
      cargo_capacity: '65',
      consumables: '2 days',
    },
    {
      _id: 14,
      name: 'Snowspeeder',
      manufacturer: 'Incom corporation',
      model: 't-47 airspeeder',
      vessel_type: 'vehicle',
      vessel_class: 'airspeeder',
      cost_in_credits: null,
      length: '4.5',
      max_atmosphering_speed: '650',
      crew: 2,
      passengers: 0,
      cargo_capacity: '10',
      consumables: 'none',
    },
    {
      _id: 16,
      name: 'TIE bomber',
      manufacturer: 'Sienar Fleet Systems',
      model: 'TIE/sa bomber',
      vessel_type: 'vehicle',
      vessel_class: 'space/planetary bomber',
      cost_in_credits: null,
      length: '7.8',
      max_atmosphering_speed: '850',
      crew: 1,
      passengers: 0,
      cargo_capacity: 'none',
      consumables: '2 days',
    },
    {
      _id: 18,
      name: 'AT-AT',
      manufacturer: 'Kuat Drive Yards, Imperial Department of Military Research',
      model: 'All Terrain Armored Transport',
      vessel_type: 'vehicle',
      vessel_class: 'assault walker',
      cost_in_credits: null,
      length: '20',
      max_atmosphering_speed: '60',
      crew: 5,
      passengers: 40,
      cargo_capacity: '1000',
      consumables: null,
    },
    {
      _id: 19,
      name: 'AT-ST',
      manufacturer: 'Kuat Drive Yards, Imperial Department of Military Research',
      model: 'All Terrain Scout Transport',
      vessel_type: 'vehicle',
      vessel_class: 'walker',
      cost_in_credits: null,
      length: '2',
      max_atmosphering_speed: '90',
      crew: 2,
      passengers: 0,
      cargo_capacity: '200',
      consumables: 'none',
    },
    {
      _id: 20,
      name: 'Storm IV Twin-Pod cloud car',
      manufacturer: 'Bespin Motors',
      model: 'Storm IV Twin-Pod',
      vessel_type: 'vehicle',
      vessel_class: 'repulsorcraft',
      cost_in_credits: '75000',
      length: '7',
      max_atmosphering_speed: '1500',
      crew: 2,
      passengers: 0,
      cargo_capacity: '10',
      consumables: '1 day',
    },
    {
      _id: 24,
      name: 'Sail barge',
      manufacturer: 'Ubrikkian Industries Custom Vehicle Division',
      model: 'Modified Luxury Sail Barge',
      vessel_type: 'vehicle',
      vessel_class: 'sail barge',
      cost_in_credits: '285000',
      length: '30',
      max_atmosphering_speed: '100',
      crew: 26,
      passengers: 500,
      cargo_capacity: '2000000',
      consumables: 'Live food tanks',
    },
    {
      _id: 25,
      name: 'Bantha-II cargo skiff',
      manufacturer: 'Ubrikkian Industries',
      model: 'Bantha-II',
      vessel_type: 'vehicle',
      vessel_class: 'repulsorcraft cargo skiff',
      cost_in_credits: '8000',
      length: '9.5',
      max_atmosphering_speed: '250',
      crew: 5,
      passengers: 16,
      cargo_capacity: '135000',
      consumables: '1 day',
    },
    {
      _id: 26,
      name: 'TIE/IN interceptor',
      manufacturer: 'Sienar Fleet Systems',
      model: 'Twin Ion Engine Interceptor',
      vessel_type: 'vehicle',
      vessel_class: 'starfighter',
      cost_in_credits: null,
      length: '9.6',
      max_atmosphering_speed: '1250',
      crew: 1,
      passengers: 0,
      cargo_capacity: '75',
      consumables: '2 days',
    },
    {
      _id: 30,
      name: 'Imperial Speeder Bike',
      manufacturer: 'Aratech Repulsor Company',
      model: '74-Z speeder bike',
      vessel_type: 'vehicle',
      vessel_class: 'speeder',
      cost_in_credits: '8000',
      length: '3',
      max_atmosphering_speed: '360',
      crew: 1,
      passengers: 1,
      cargo_capacity: '4',
      consumables: '1 day',
    },
    {
      _id: 33,
      name: 'Vulture Droid',
      manufacturer: 'Haor Chall Engineering, Baktoid Armor Workshop',
      model: 'Vulture-class droid starfighter',
      vessel_type: 'vehicle',
      vessel_class: 'starfighter',
      cost_in_credits: null,
      length: '3.5',
      max_atmosphering_speed: '1200',
      crew: 0,
      passengers: 0,
      cargo_capacity: '0',
      consumables: 'none',
    },
    {
      _id: 34,
      name: 'Multi-Troop Transport',
      manufacturer: 'Baktoid Armor Workshop',
      model: 'Multi-Troop Transport',
      vessel_type: 'vehicle',
      vessel_class: 'repulsorcraft',
      cost_in_credits: '138000',
      length: '31',
      max_atmosphering_speed: '35',
      crew: 4,
      passengers: 112,
      cargo_capacity: '12000',
      consumables: null,
    },
    {
      _id: 35,
      name: 'Armored Assault Tank',
      manufacturer: 'Baktoid Armor Workshop',
      model: 'Armoured Assault Tank',
      vessel_type: 'vehicle',
      vessel_class: 'repulsorcraft',
      cost_in_credits: null,
      length: '9.75',
      max_atmosphering_speed: '55',
      crew: 4,
      passengers: 6,
      cargo_capacity: null,
      consumables: null,
    },
    {
      _id: 36,
      name: 'Single Trooper Aerial Platform',
      manufacturer: 'Baktoid Armor Workshop',
      model: 'Single Trooper Aerial Platform',
      vessel_type: 'vehicle',
      vessel_class: 'repulsorcraft',
      cost_in_credits: '2500',
      length: '2',
      max_atmosphering_speed: '400',
      crew: 1,
      passengers: 0,
      cargo_capacity: 'none',
      consumables: 'none',
    },
    {
      _id: 37,
      name: 'C-9979 landing craft',
      manufacturer: 'Haor Chall Engineering',
      model: 'C-9979 landing craft',
      vessel_type: 'vehicle',
      vessel_class: 'landing craft',
      cost_in_credits: '200000',
      length: '210',
      max_atmosphering_speed: '587',
      crew: 140,
      passengers: 284,
      cargo_capacity: '1800000',
      consumables: '1 day',
    },
    {
      _id: 38,
      name: 'Tribubble bongo',
      manufacturer: 'Otoh Gunga Bongameken Cooperative',
      model: 'Tribubble bongo',
      vessel_type: 'vehicle',
      vessel_class: 'submarine',
      cost_in_credits: null,
      length: '15',
      max_atmosphering_speed: '85',
      crew: 1,
      passengers: 2,
      cargo_capacity: '1600',
      consumables: null,
    },
    {
      _id: 42,
      name: 'Sith speeder',
      manufacturer: 'Razalon',
      model: 'FC-20 speeder bike',
      vessel_type: 'vehicle',
      vessel_class: 'speeder',
      cost_in_credits: '4000',
      length: '1.5',
      max_atmosphering_speed: '180',
      crew: 1,
      passengers: 0,
      cargo_capacity: '2',
      consumables: null,
    },
    {
      _id: 44,
      name: 'Zephyr-G swoop bike',
      manufacturer: 'Mobquet Swoops and Speeders',
      model: 'Zephyr-G swoop bike',
      vessel_type: 'vehicle',
      vessel_class: 'repulsorcraft',
      cost_in_credits: '5750',
      length: '3.68',
      max_atmosphering_speed: '350',
      crew: 1,
      passengers: 1,
      cargo_capacity: '200',
      consumables: 'none',
    },
    {
      _id: 45,
      name: 'Koro-2 Exodrive airspeeder',
      manufacturer: 'Desler Gizh Outworld Mobility Corporation',
      model: 'Koro-2 Exodrive airspeeder',
      vessel_type: 'vehicle',
      vessel_class: 'airspeeder',
      cost_in_credits: null,
      length: '6.6',
      max_atmosphering_speed: '800',
      crew: 1,
      passengers: 1,
      cargo_capacity: '80',
      consumables: null,
    },
    {
      _id: 46,
      name: 'XJ-6 airspeeder',
      manufacturer: 'Narglatch AirTech prefabricated kit',
      model: 'XJ-6 airspeeder',
      vessel_type: 'vehicle',
      vessel_class: 'airspeeder',
      cost_in_credits: null,
      length: '6.23',
      max_atmosphering_speed: '720',
      crew: 1,
      passengers: 1,
      cargo_capacity: null,
      consumables: null,
    },
    {
      _id: 50,
      name: 'LAAT/i',
      manufacturer: 'Rothana Heavy Engineering',
      model: 'Low Altitude Assault Transport/infrantry',
      vessel_type: 'vehicle',
      vessel_class: 'gunship',
      cost_in_credits: null,
      length: '17.4',
      max_atmosphering_speed: '620',
      crew: 6,
      passengers: 30,
      cargo_capacity: '170',
      consumables: null,
    },
    {
      _id: 51,
      name: 'LAAT/c',
      manufacturer: 'Rothana Heavy Engineering',
      model: 'Low Altitude Assault Transport/carrier',
      vessel_type: 'vehicle',
      vessel_class: 'gunship',
      cost_in_credits: null,
      length: '28.82',
      max_atmosphering_speed: '620',
      crew: 1,
      passengers: 0,
      cargo_capacity: '40000',
      consumables: null,
    },
    {
      _id: 60,
      name: 'Tsmeu-6 personal wheel bike',
      manufacturer: 'Z-Gomot Ternbuell Guppat Corporation',
      model: 'Tsmeu-6 personal wheel bike',
      vessel_type: 'vehicle',
      vessel_class: 'wheeled walker',
      cost_in_credits: '15000',
      length: '3.5',
      max_atmosphering_speed: '330',
      crew: 1,
      passengers: 1,
      cargo_capacity: '10',
      consumables: 'none',
    },
    {
      _id: 62,
      name: 'Emergency Firespeeder',
      manufacturer: null,
      model: 'Fire suppression speeder',
      vessel_type: 'vehicle',
      vessel_class: 'fire suppression ship',
      cost_in_credits: null,
      length: null,
      max_atmosphering_speed: null,
      crew: 2,
      passengers: null,
      cargo_capacity: null,
      consumables: null,
    },
    {
      _id: 67,
      name: 'Droid tri-fighter',
      manufacturer: 'Colla Designs, Phlac-Arphocc Automata Industries',
      model: 'tri-fighter',
      vessel_type: 'vehicle',
      vessel_class: 'droid starfighter',
      cost_in_credits: '20000',
      length: '5.4',
      max_atmosphering_speed: '1180',
      crew: 1,
      passengers: 0,
      cargo_capacity: '0',
      consumables: 'none',
    },
    {
      _id: 69,
      name: 'Oevvaor jet catamaran',
      manufacturer: 'Appazanna Engineering Works',
      model: 'Oevvaor jet catamaran',
      vessel_type: 'vehicle',
      vessel_class: 'airspeeder',
      cost_in_credits: '12125',
      length: '15.1',
      max_atmosphering_speed: '420',
      crew: 2,
      passengers: 2,
      cargo_capacity: '50',
      consumables: '3 days',
    },
    {
      _id: 70,
      name: 'Raddaugh Gnasp fluttercraft',
      manufacturer: 'Appazanna Engineering Works',
      model: 'Raddaugh Gnasp fluttercraft',
      vessel_type: 'vehicle',
      vessel_class: 'air speeder',
      cost_in_credits: '14750',
      length: '7',
      max_atmosphering_speed: '310',
      crew: 2,
      passengers: 0,
      cargo_capacity: '20',
      consumables: 'none',
    },
    {
      _id: 71,
      name: 'Clone turbo tank',
      manufacturer: 'Kuat Drive Yards',
      model: 'HAVw A6 Juggernaut',
      vessel_type: 'vehicle',
      vessel_class: 'wheeled walker',
      cost_in_credits: '350000',
      length: '49.4',
      max_atmosphering_speed: '160',
      crew: 20,
      passengers: 300,
      cargo_capacity: '30000',
      consumables: '20 days',
    },
    {
      _id: 72,
      name: 'Corporate Alliance tank droid',
      manufacturer: 'Techno Union',
      model: 'NR-N99 Persuader-class droid enforcer',
      vessel_type: 'vehicle',
      vessel_class: 'droid tank',
      cost_in_credits: '49000',
      length: '10.96',
      max_atmosphering_speed: '100',
      crew: 0,
      passengers: 4,
      cargo_capacity: 'none',
      consumables: 'none',
    },
    {
      _id: 73,
      name: 'Droid gunship',
      manufacturer: 'Baktoid Fleet Ordnance, Haor Chall Engineering',
      model: 'HMP droid gunship',
      vessel_type: 'vehicle',
      vessel_class: 'airspeeder',
      cost_in_credits: '60000',
      length: '12.3',
      max_atmosphering_speed: '820',
      crew: 0,
      passengers: 0,
      cargo_capacity: '0',
      consumables: 'none',
    },
    {
      _id: 76,
      name: 'AT-RT',
      manufacturer: 'Kuat Drive Yards',
      model: 'All Terrain Recon Transport',
      vessel_type: 'vehicle',
      vessel_class: 'walker',
      cost_in_credits: '40000',
      length: '3.2',
      max_atmosphering_speed: '90',
      crew: 1,
      passengers: 0,
      cargo_capacity: '20',
      consumables: '1 day',
    },
    {
      _id: 53,
      name: 'AT-TE',
      manufacturer: 'Rothana Heavy Engineering, Kuat Drive Yards',
      model: 'All Terrain Tactical Enforcer',
      vessel_type: 'vehicle',
      vessel_class: 'walker',
      cost_in_credits: null,
      length: '13.2',
      max_atmosphering_speed: '60',
      crew: 6,
      passengers: 36,
      cargo_capacity: '10000',
      consumables: '21 days',
    },
    {
      _id: 54,
      name: 'SPHA',
      manufacturer: 'Rothana Heavy Engineering',
      model: 'Self-Propelled Heavy Artillery',
      vessel_type: 'vehicle',
      vessel_class: 'walker',
      cost_in_credits: null,
      length: '140',
      max_atmosphering_speed: '35',
      crew: 25,
      passengers: 30,
      cargo_capacity: '500',
      consumables: '7 days',
    },
    {
      _id: 55,
      name: 'Flitknot speeder',
      manufacturer: 'Huppla Pasa Tisc Shipwrights Collective',
      model: 'Flitknot speeder',
      vessel_type: 'vehicle',
      vessel_class: 'speeder',
      cost_in_credits: '8000',
      length: '2',
      max_atmosphering_speed: '634',
      crew: 1,
      passengers: 0,
      cargo_capacity: null,
      consumables: null,
    },
    {
      _id: 56,
      name: 'Neimoidian shuttle',
      manufacturer: 'Haor Chall Engineering',
      model: 'Sheathipede-class transport shuttle',
      vessel_type: 'vehicle',
      vessel_class: 'transport',
      cost_in_credits: null,
      length: '20',
      max_atmosphering_speed: '880',
      crew: 2,
      passengers: 6,
      cargo_capacity: '1000',
      consumables: '7 days',
    },
    {
      _id: 57,
      name: 'Geonosian starfighter',
      manufacturer: 'Huppla Pasa Tisc Shipwrights Collective',
      model: 'Nantex-class territorial defense',
      vessel_type: 'vehicle',
      vessel_class: 'starfighter',
      cost_in_credits: null,
      length: '9.8',
      max_atmosphering_speed: '20000',
      crew: 1,
      passengers: 0,
      cargo_capacity: null,
      consumables: null,
    },
    {
      _id: 15,
      name: 'Executor',
      manufacturer: 'Kuat Drive Yards, Fondor Shipyards',
      model: 'Executor-class star dreadnought',
      vessel_type: 'starship',
      vessel_class: 'Star dreadnought',
      cost_in_credits: '1143350000',
      length: '19000',
      max_atmosphering_speed: 'n/a',
      crew: 279144,
      passengers: 38000,
      cargo_capacity: '250000000',
      consumables: '6 years',
    },
    {
      _id: 5,
      name: 'Sentinel-class landing craft',
      manufacturer: 'Sienar Fleet Systems, Cyngus Spaceworks',
      model: 'Sentinel-class landing craft',
      vessel_type: 'starship',
      vessel_class: 'landing craft',
      cost_in_credits: '240000',
      length: '38',
      max_atmosphering_speed: '1000',
      crew: 5,
      passengers: 75,
      cargo_capacity: '180000',
      consumables: '1 month',
    },
    {
      _id: 9,
      name: 'Death Star',
      manufacturer: 'Imperial Department of Military Research, Sienar Fleet Systems',
      model: 'DS-1 Orbital Battle Station',
      vessel_type: 'starship',
      vessel_class: 'Deep Space Mobile Battlestation',
      cost_in_credits: '1000000000000',
      length: '120000',
      max_atmosphering_speed: 'n/a',
      crew: 342953,
      passengers: 843342,
      cargo_capacity: '1000000000000',
      consumables: '3 years',
    },
    {
      _id: 10,
      name: 'Millennium Falcon',
      manufacturer: 'Corellian Engineering Corporation',
      model: 'YT-1300 light freighter',
      vessel_type: 'starship',
      vessel_class: 'Light freighter',
      cost_in_credits: '100000',
      length: '34.37',
      max_atmosphering_speed: '1050',
      crew: 4,
      passengers: 6,
      cargo_capacity: '100000',
      consumables: '2 months',
    },
    {
      _id: 11,
      name: 'Y-wing',
      manufacturer: 'Koensayr Manufacturing',
      model: 'BTL Y-wing',
      vessel_type: 'starship',
      vessel_class: 'assault starfighter',
      cost_in_credits: '134999',
      length: '14',
      max_atmosphering_speed: '1000km',
      crew: 2,
      passengers: 0,
      cargo_capacity: '110',
      consumables: '1 week',
    },
    {
      _id: 12,
      name: 'X-wing',
      manufacturer: 'Incom Corporation',
      model: 'T-65 X-wing',
      vessel_type: 'starship',
      vessel_class: 'Starfighter',
      cost_in_credits: '149999',
      length: '12.5',
      max_atmosphering_speed: '1050',
      crew: 1,
      passengers: 0,
      cargo_capacity: '110',
      consumables: '1 week',
    },
    {
      _id: 13,
      name: 'TIE Advanced x1',
      manufacturer: 'Sienar Fleet Systems',
      model: 'Twin Ion Engine Advanced x1',
      vessel_type: 'starship',
      vessel_class: 'Starfighter',
      cost_in_credits: null,
      length: '9.2',
      max_atmosphering_speed: '1200',
      crew: 1,
      passengers: 0,
      cargo_capacity: '150',
      consumables: '5 days',
    },
    {
      _id: 21,
      name: 'Slave 1',
      manufacturer: 'Kuat Systems Engineering',
      model: 'Firespray-31-class patrol and attack',
      vessel_type: 'starship',
      vessel_class: 'Patrol craft',
      cost_in_credits: null,
      length: '21.5',
      max_atmosphering_speed: '1000',
      crew: 1,
      passengers: 6,
      cargo_capacity: '70000',
      consumables: '1 month',
    },
    {
      _id: 22,
      name: 'Imperial shuttle',
      manufacturer: 'Sienar Fleet Systems',
      model: 'Lambda-class T-4a shuttle',
      vessel_type: 'starship',
      vessel_class: 'Armed government transport',
      cost_in_credits: '240000',
      length: '20',
      max_atmosphering_speed: '850',
      crew: 6,
      passengers: 20,
      cargo_capacity: '80000',
      consumables: '2 months',
    },
    {
      _id: 23,
      name: 'EF76 Nebulon-B escort frigate',
      manufacturer: 'Kuat Drive Yards',
      model: 'EF76 Nebulon-B escort frigate',
      vessel_type: 'starship',
      vessel_class: 'Escort ship',
      cost_in_credits: '8500000',
      length: '300',
      max_atmosphering_speed: '800',
      crew: 854,
      passengers: 75,
      cargo_capacity: '6000000',
      consumables: '2 years',
    },
    {
      _id: 27,
      name: 'Calamari Cruiser',
      manufacturer: 'Mon Calamari shipyards',
      model: 'MC80 Liberty type Star Cruiser',
      vessel_type: 'starship',
      vessel_class: 'Star Cruiser',
      cost_in_credits: '104000000',
      length: '1200',
      max_atmosphering_speed: 'n/a',
      crew: 5400,
      passengers: 1200,
      cargo_capacity: null,
      consumables: '2 years',
    },
    {
      _id: 28,
      name: 'A-wing',
      manufacturer: 'Alliance Underground Engineering, Incom Corporation',
      model: 'RZ-1 A-wing Interceptor',
      vessel_type: 'starship',
      vessel_class: 'Starfighter',
      cost_in_credits: '175000',
      length: '9.6',
      max_atmosphering_speed: '1300',
      crew: 1,
      passengers: 0,
      cargo_capacity: '40',
      consumables: '1 week',
    },
    {
      _id: 29,
      name: 'B-wing',
      manufacturer: 'Slayn & Korpil',
      model: 'A/SF-01 B-wing starfighter',
      vessel_type: 'starship',
      vessel_class: 'Assault Starfighter',
      cost_in_credits: '220000',
      length: '16.9',
      max_atmosphering_speed: '950',
      crew: 1,
      passengers: 0,
      cargo_capacity: '45',
      consumables: '1 week',
    },
    {
      _id: 31,
      name: 'Republic Cruiser',
      manufacturer: 'Corellian Engineering Corporation',
      model: 'Consular-class cruiser',
      vessel_type: 'starship',
      vessel_class: 'Space cruiser',
      cost_in_credits: null,
      length: '115',
      max_atmosphering_speed: '900',
      crew: 9,
      passengers: 16,
      cargo_capacity: null,
      consumables: null,
    },
    {
      _id: 39,
      name: 'Naboo fighter',
      manufacturer: 'Theed Palace Space Vessel Engineering Corps',
      model: 'N-1 starfighter',
      vessel_type: 'starship',
      vessel_class: 'Starfighter',
      cost_in_credits: '200000',
      length: '11',
      max_atmosphering_speed: '1100',
      crew: 1,
      passengers: 0,
      cargo_capacity: '65',
      consumables: '7 days',
    },
    {
      _id: 40,
      name: 'Naboo Royal Starship',
      manufacturer: 'Theed Palace Space Vessel Engineering Corps, Nubia Star Drives',
      model: 'J-type 327 Nubian royal starship',
      vessel_type: 'starship',
      vessel_class: 'yacht',
      cost_in_credits: null,
      length: '76',
      max_atmosphering_speed: '920',
      crew: 8,
      passengers: null,
      cargo_capacity: null,
      consumables: null,
    },
    {
      _id: 41,
      name: 'Scimitar',
      manufacturer: 'Republic Sienar Systems',
      model: 'Star Courier',
      vessel_type: 'starship',
      vessel_class: 'Space Transport',
      cost_in_credits: '55000000',
      length: '26.5',
      max_atmosphering_speed: '1180',
      crew: 1,
      passengers: 6,
      cargo_capacity: '2500000',
      consumables: '30 days',
    },
    {
      _id: 43,
      name: 'J-type diplomatic barge',
      manufacturer: 'Theed Palace Space Vessel Engineering Corps, Nubia Star Drives',
      model: 'J-type diplomatic barge',
      vessel_type: 'starship',
      vessel_class: 'Diplomatic barge',
      cost_in_credits: '2000000',
      length: '39',
      max_atmosphering_speed: '2000',
      crew: 5,
      passengers: 10,
      cargo_capacity: null,
      consumables: '1 year',
    },
    {
      _id: 47,
      name: 'AA-9 Coruscant freighter',
      manufacturer: 'Botajef Shipyards',
      model: 'Botajef AA-9 Freighter-Liner',
      vessel_type: 'starship',
      vessel_class: 'freighter',
      cost_in_credits: null,
      length: '390',
      max_atmosphering_speed: null,
      crew: null,
      passengers: 30000,
      cargo_capacity: null,
      consumables: null,
    },
    {
      _id: 48,
      name: 'Jedi starfighter',
      manufacturer: 'Kuat Systems Engineering',
      model: 'Delta-7 Aethersprite-class interceptor',
      vessel_type: 'starship',
      vessel_class: 'Starfighter',
      cost_in_credits: '180000',
      length: '8',
      max_atmosphering_speed: '1150',
      crew: 1,
      passengers: 0,
      cargo_capacity: '60',
      consumables: '7 days',
    },
    {
      _id: 49,
      name: 'H-type Nubian yacht',
      manufacturer: 'Theed Palace Space Vessel Engineering Corps',
      model: 'H-type Nubian yacht',
      vessel_type: 'starship',
      vessel_class: 'yacht',
      cost_in_credits: null,
      length: '47.9',
      max_atmosphering_speed: '8000',
      crew: 4,
      passengers: null,
      cargo_capacity: null,
      consumables: null,
    },
    {
      _id: 3,
      name: 'Star Destroyer',
      manufacturer: 'Kuat Drive Yards',
      model: 'Imperial I-class Star Destroyer',
      vessel_type: 'starship',
      vessel_class: 'Star Destroyer',
      cost_in_credits: '150000000',
      length: '1,600',
      max_atmosphering_speed: '975',
      crew: 47060,
      passengers: 0,
      cargo_capacity: '36000000',
      consumables: '2 years',
    },
    {
      _id: 59,
      name: 'Trade Federation cruiser',
      manufacturer: 'Rendili StarDrive, Free Dac Volunteers Engineering corps.',
      model: 'Providence-class carrier/destroyer',
      vessel_type: 'starship',
      vessel_class: 'capital ship',
      cost_in_credits: '125000000',
      length: '1088',
      max_atmosphering_speed: '1050',
      crew: 600,
      passengers: 48247,
      cargo_capacity: '50000000',
      consumables: '4 years',
    },
    {
      _id: 61,
      name: 'Theta-class T-2c shuttle',
      manufacturer: 'Cygnus Spaceworks',
      model: 'Theta-class T-2c shuttle',
      vessel_type: 'starship',
      vessel_class: 'transport',
      cost_in_credits: '1000000',
      length: '18.5',
      max_atmosphering_speed: '2000',
      crew: 5,
      passengers: 16,
      cargo_capacity: '50000',
      consumables: '56 days',
    },
    {
      _id: 77,
      name: 'T-70 X-wing fighter',
      manufacturer: 'Incom',
      model: 'T-70 X-wing fighter',
      vessel_type: 'starship',
      vessel_class: 'fighter',
      cost_in_credits: null,
      length: null,
      max_atmosphering_speed: null,
      crew: 1,
      passengers: null,
      cargo_capacity: null,
      consumables: null,
    },
    {
      _id: 17,
      name: 'Rebel transport',
      manufacturer: 'Gallofree Yards, Inc.',
      model: 'GR-75 medium transport',
      vessel_type: 'starship',
      vessel_class: 'Medium transport',
      cost_in_credits: null,
      length: '90',
      max_atmosphering_speed: '650',
      crew: 6,
      passengers: 90,
      cargo_capacity: '19000000',
      consumables: '6 months',
    },
    {
      _id: 32,
      name: 'Droid control ship',
      manufacturer: 'Hoersch-Kessel Drive, Inc.',
      model: 'Lucrehulk-class Droid Control Ship',
      vessel_type: 'starship',
      vessel_class: 'Droid control ship',
      cost_in_credits: null,
      length: '3170',
      max_atmosphering_speed: 'n/a',
      crew: 175,
      passengers: 139000,
      cargo_capacity: '4000000000',
      consumables: '500 days',
    },
    {
      _id: 52,
      name: 'Republic Assault ship',
      manufacturer: 'Rothana Heavy Engineering',
      model: 'Acclamator I-class assault ship',
      vessel_type: 'starship',
      vessel_class: 'assault ship',
      cost_in_credits: null,
      length: '752',
      max_atmosphering_speed: null,
      crew: 700,
      passengers: 16000,
      cargo_capacity: '11250000',
      consumables: '2 years',
    },
    {
      _id: 58,
      name: 'Solar Sailer',
      manufacturer: 'Huppla Pasa Tisc Shipwrights Collective',
      model: 'Punworcca 116-class interstellar sloop',
      vessel_type: 'starship',
      vessel_class: 'yacht',
      cost_in_credits: '35700',
      length: '15.2',
      max_atmosphering_speed: '1600',
      crew: 3,
      passengers: 11,
      cargo_capacity: '240',
      consumables: '7 days',
    },
    {
      _id: 63,
      name: 'Republic attack cruiser',
      manufacturer: 'Kuat Drive Yards, Allanteen Six shipyards',
      model: 'Senator-class Star Destroyer',
      vessel_type: 'starship',
      vessel_class: 'star destroyer',
      cost_in_credits: '59000000',
      length: '1137',
      max_atmosphering_speed: '975',
      crew: 7400,
      passengers: 2000,
      cargo_capacity: '20000000',
      consumables: '2 years',
    },
    {
      _id: 64,
      name: 'Naboo star skiff',
      manufacturer:
        'Theed Palace Space Vessel Engineering Corps/Nubia Star Drives, Incorporated',
      model: 'J-type star skiff',
      vessel_type: 'starship',
      vessel_class: 'yacht',
      cost_in_credits: null,
      length: '29.2',
      max_atmosphering_speed: '1050',
      crew: 3,
      passengers: 3,
      cargo_capacity: null,
      consumables: null,
    },
    {
      _id: 65,
      name: 'Jedi Interceptor',
      manufacturer: 'Kuat Systems Engineering',
      model: 'Eta-2 Actis-class light interceptor',
      vessel_type: 'starship',
      vessel_class: 'starfighter',
      cost_in_credits: '320000',
      length: '5.47',
      max_atmosphering_speed: '1500',
      crew: 1,
      passengers: 0,
      cargo_capacity: '60',
      consumables: '2 days',
    },
    {
      _id: 66,
      name: 'arc-170',
      manufacturer: 'Incom Corporation, Subpro Corporation',
      model: 'Aggressive Reconnaissance-170 starfighte',
      vessel_type: 'starship',
      vessel_class: 'starfighter',
      cost_in_credits: '155000',
      length: '14.5',
      max_atmosphering_speed: '1000',
      crew: 3,
      passengers: 0,
      cargo_capacity: '110',
      consumables: '5 days',
    },
    {
      _id: 74,
      name: 'Belbullab-22 starfighter',
      manufacturer: 'Feethan Ottraw Scalable Assemblies',
      model: 'Belbullab-22 starfighter',
      vessel_type: 'starship',
      vessel_class: 'starfighter',
      cost_in_credits: '168000',
      length: '6.71',
      max_atmosphering_speed: '1100',
      crew: 1,
      passengers: 0,
      cargo_capacity: '140',
      consumables: '7 days',
    },
    {
      _id: 75,
      name: 'V-wing',
      manufacturer: 'Kuat Systems Engineering',
      model: 'Alpha-3 Nimbus-class V-wing starfighter',
      vessel_type: 'starship',
      vessel_class: 'starfighter',
      cost_in_credits: '102500',
      length: '7.9',
      max_atmosphering_speed: '1050',
      crew: 1,
      passengers: 0,
      cargo_capacity: '60',
      consumables: '15 hours',
    },
    {
      _id: 2,
      name: 'CR90 corvette',
      manufacturer: 'Corellian Engineering Corporation',
      model: 'CR90 corvette',
      vessel_type: 'starship',
      vessel_class: 'corvette',
      cost_in_credits: '3500000',
      length: '150',
      max_atmosphering_speed: '950',
      crew: 165,
      passengers: 600,
      cargo_capacity: '3000000',
      consumables: '1 year',
    },
    {
      _id: 68,
      name: 'Banking clan frigate',
      manufacturer: 'Hoersch-Kessel Drive, Inc, Gwori Revolutionary Industries',
      model: 'Munificent-class star frigate',
      vessel_type: 'starship',
      vessel_class: 'cruiser',
      cost_in_credits: '57000000',
      length: '825',
      max_atmosphering_speed: null,
      crew: 200,
      passengers: null,
      cargo_capacity: '40000000',
      consumables: '2 years',
    },
  ],
  'public.vessels_in_films': [],
  'public.starship_specs': [
    { _id: 1, hyperdrive_rating: '2.0', MGLT: '40', vessel_id: '15' },
    { _id: 2, hyperdrive_rating: '1.0', MGLT: '70', vessel_id: '5' },
    { _id: 3, hyperdrive_rating: '4.0', MGLT: '10', vessel_id: '9' },
    { _id: 4, hyperdrive_rating: '0.5', MGLT: '75', vessel_id: '10' },
    { _id: 5, hyperdrive_rating: '1.0', MGLT: '80', vessel_id: '11' },
    { _id: 6, hyperdrive_rating: '1.0', MGLT: '100', vessel_id: '12' },
    { _id: 7, hyperdrive_rating: '1.0', MGLT: '105', vessel_id: '13' },
    { _id: 8, hyperdrive_rating: '3.0', MGLT: '70', vessel_id: '21' },
    { _id: 9, hyperdrive_rating: '1.0', MGLT: '50', vessel_id: '22' },
    { _id: 10, hyperdrive_rating: '2.0', MGLT: '40', vessel_id: '23' },
    { _id: 11, hyperdrive_rating: '1.0', MGLT: '60', vessel_id: '27' },
    { _id: 12, hyperdrive_rating: '1.0', MGLT: '120', vessel_id: '28' },
    { _id: 13, hyperdrive_rating: '2.0', MGLT: '91', vessel_id: '29' },
    { _id: 14, hyperdrive_rating: '2.0', MGLT: null, vessel_id: '31' },
    { _id: 15, hyperdrive_rating: '1.0', MGLT: null, vessel_id: '39' },
    { _id: 16, hyperdrive_rating: '1.8', MGLT: null, vessel_id: '40' },
    { _id: 17, hyperdrive_rating: '1.5', MGLT: null, vessel_id: '41' },
    { _id: 18, hyperdrive_rating: '0.7', MGLT: null, vessel_id: '43' },
    { _id: 19, hyperdrive_rating: null, MGLT: null, vessel_id: '47' },
    { _id: 20, hyperdrive_rating: '1.0', MGLT: null, vessel_id: '48' },
    { _id: 21, hyperdrive_rating: '0.9', MGLT: null, vessel_id: '49' },
    { _id: 22, hyperdrive_rating: '2.0', MGLT: '60', vessel_id: '3' },
    { _id: 23, hyperdrive_rating: '1.5', MGLT: null, vessel_id: '59' },
    { _id: 24, hyperdrive_rating: '1.0', MGLT: null, vessel_id: '61' },
    { _id: 25, hyperdrive_rating: null, MGLT: null, vessel_id: '77' },
    { _id: 26, hyperdrive_rating: '4.0', MGLT: '20', vessel_id: '17' },
    { _id: 27, hyperdrive_rating: '2.0', MGLT: null, vessel_id: '32' },
    { _id: 28, hyperdrive_rating: '0.6', MGLT: null, vessel_id: '52' },
    { _id: 29, hyperdrive_rating: '1.5', MGLT: null, vessel_id: '58' },
    { _id: 30, hyperdrive_rating: '1.0', MGLT: null, vessel_id: '63' },
    { _id: 31, hyperdrive_rating: '0.5', MGLT: null, vessel_id: '64' },
    { _id: 32, hyperdrive_rating: '1.0', MGLT: null, vessel_id: '65' },
    { _id: 33, hyperdrive_rating: '1.0', MGLT: '100', vessel_id: '66' },
    { _id: 34, hyperdrive_rating: '6', MGLT: null, vessel_id: '74' },
    { _id: 35, hyperdrive_rating: '1.0', MGLT: null, vessel_id: '75' },
    { _id: 36, hyperdrive_rating: '2.0', MGLT: '60', vessel_id: '2' },
    { _id: 37, hyperdrive_rating: '1.0', MGLT: null, vessel_id: '68' },
  ],
};

export const swapiDataString = JSON.stringify(swapiData);
